//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace OSGeo.OSR {

using global::System;
using global::System.Runtime.InteropServices;

public class AreaOfUse : global::System.IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;
  protected object swigParentRef;

  protected static object ThisOwn_true() { return null; }
  protected object ThisOwn_false() { return this; }

  public AreaOfUse(IntPtr cPtr, bool cMemoryOwn, object parent) {
    swigCMemOwn = cMemoryOwn;
    swigParentRef = parent;
    swigCPtr = new HandleRef(this, cPtr);
  }

  public static HandleRef getCPtr(AreaOfUse obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }
  public static HandleRef getCPtrAndDisown(AreaOfUse obj, object parent) {
    if (obj != null)
    {
      obj.swigCMemOwn = false;
      obj.swigParentRef = parent;
      return obj.swigCPtr;
    }
    else
    {
      return new HandleRef(null, IntPtr.Zero);
    }
  }
  public static HandleRef getCPtrAndSetReference(AreaOfUse obj, object parent) {
    if (obj != null)
    {
      obj.swigParentRef = parent;
      return obj.swigCPtr;
    }
    else
    {
      return new HandleRef(null, IntPtr.Zero);
    }
  }

  ~AreaOfUse() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          OsrPINVOKE.delete_AreaOfUse(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public double west_lon_degree {
    get {
      double ret = OsrPINVOKE.AreaOfUse_west_lon_degree_get(swigCPtr);
      if (OsrPINVOKE.SWIGPendingException.Pending) throw OsrPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public double south_lat_degree {
    get {
      double ret = OsrPINVOKE.AreaOfUse_south_lat_degree_get(swigCPtr);
      if (OsrPINVOKE.SWIGPendingException.Pending) throw OsrPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public double east_lon_degree {
    get {
      double ret = OsrPINVOKE.AreaOfUse_east_lon_degree_get(swigCPtr);
      if (OsrPINVOKE.SWIGPendingException.Pending) throw OsrPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public double north_lat_degree {
    get {
      double ret = OsrPINVOKE.AreaOfUse_north_lat_degree_get(swigCPtr);
      if (OsrPINVOKE.SWIGPendingException.Pending) throw OsrPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public string name {
    get {
      string ret = OsrPINVOKE.AreaOfUse_name_get(swigCPtr);
      if (OsrPINVOKE.SWIGPendingException.Pending) throw OsrPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public AreaOfUse(double west_lon_degree, double south_lat_degree, double east_lon_degree, double north_lat_degree, string name) : this(OsrPINVOKE.new_AreaOfUse(west_lon_degree, south_lat_degree, east_lon_degree, north_lat_degree, name), true, null) {
    if (OsrPINVOKE.SWIGPendingException.Pending) throw OsrPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
