//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace OSGeo.GDAL {

using global::System;
using global::System.Runtime.InteropServices;

public class Driver : MajorObject {
  private HandleRef swigCPtr;

  public Driver(IntPtr cPtr, bool cMemoryOwn, object parent) : base(GdalPINVOKE.Driver_SWIGUpcast(cPtr), cMemoryOwn, parent) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  public static HandleRef getCPtr(Driver obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }
  public static HandleRef getCPtrAndDisown(Driver obj, object parent) {
    if (obj != null)
    {
      obj.swigCMemOwn = false;
      obj.swigParentRef = parent;
      return obj.swigCPtr;
    }
    else
    {
      return new HandleRef(null, IntPtr.Zero);
    }
  }
  public static HandleRef getCPtrAndSetReference(Driver obj, object parent) {
    if (obj != null)
    {
      obj.swigParentRef = parent;
      return obj.swigCPtr;
    }
    else
    {
      return new HandleRef(null, IntPtr.Zero);
    }
  }

  ~Driver() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          throw new global::System.MethodAccessException("C++ destructor does not have public access");
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public string ShortName {
  get {
    /* %typemap(csvarout) (char *), (char *&), (char[ANY]), (char[]), (const char *utf8_string) */
    IntPtr cPtr = GdalPINVOKE.Driver_ShortName_get(swigCPtr);
    string ret = GdalPINVOKE.LengthPrefixedUtf16UnmanagedToString(cPtr);
    
      if (GdalPINVOKE.SWIGPendingException.Pending) throw GdalPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  }

  public string LongName {
  get {
    /* %typemap(csvarout) (char *), (char *&), (char[ANY]), (char[]), (const char *utf8_string) */
    IntPtr cPtr = GdalPINVOKE.Driver_LongName_get(swigCPtr);
    string ret = GdalPINVOKE.LengthPrefixedUtf16UnmanagedToString(cPtr);
    
      if (GdalPINVOKE.SWIGPendingException.Pending) throw GdalPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  }

  public string HelpTopic {
  get {
    /* %typemap(csvarout) (char *), (char *&), (char[ANY]), (char[]), (const char *utf8_string) */
    IntPtr cPtr = GdalPINVOKE.Driver_HelpTopic_get(swigCPtr);
    string ret = GdalPINVOKE.LengthPrefixedUtf16UnmanagedToString(cPtr);
    
      if (GdalPINVOKE.SWIGPendingException.Pending) throw GdalPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  }

  public Dataset Create(string path, int xsize, int ysize, int bands, DataType eType, string[] options) {
    IntPtr temppath = GdalPINVOKE.StringToUtf8Unmanaged(path);
    using (var tempoptions = new GdalPINVOKE.StringListMarshal(options)) { 
    try {
      IntPtr cPtr = GdalPINVOKE.Driver_Create(swigCPtr, temppath, xsize, ysize, bands, (int)eType, tempoptions._ar);
      Dataset ret = (cPtr == IntPtr.Zero) ? null : new Dataset(cPtr, true, ThisOwn_true());
      if (GdalPINVOKE.SWIGPendingException.Pending) throw GdalPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } finally {
    System.Runtime.InteropServices.Marshal.FreeHGlobal(temppath);
    }
    }
  }

  public Dataset CreateVector(string path, string[] options) {
    IntPtr temppath = GdalPINVOKE.StringToUtf8Unmanaged(path);
    using (var tempoptions = new GdalPINVOKE.StringListMarshal(options)) { 
    try {
      IntPtr cPtr = GdalPINVOKE.Driver_CreateVector(swigCPtr, temppath, tempoptions._ar);
      Dataset ret = (cPtr == IntPtr.Zero) ? null : new Dataset(cPtr, true, ThisOwn_true());
      if (GdalPINVOKE.SWIGPendingException.Pending) throw GdalPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } finally {
    System.Runtime.InteropServices.Marshal.FreeHGlobal(temppath);
    }
    }
  }

  public Dataset CreateMultiDimensional(string path, string[] root_group_options, string[] options) {
    IntPtr temppath = GdalPINVOKE.StringToUtf8Unmanaged(path);
    using (var temproot_group_options = new GdalPINVOKE.StringListMarshal(root_group_options)) { 
    using (var tempoptions = new GdalPINVOKE.StringListMarshal(options)) { 
    try {
      IntPtr cPtr = GdalPINVOKE.Driver_CreateMultiDimensional(swigCPtr, temppath, temproot_group_options._ar, tempoptions._ar);
      Dataset ret = (cPtr == IntPtr.Zero) ? null : new Dataset(cPtr, true, ThisOwn_true());
      if (GdalPINVOKE.SWIGPendingException.Pending) throw GdalPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } finally {
    System.Runtime.InteropServices.Marshal.FreeHGlobal(temppath);
    }
    }
    }
  }

  public Dataset CreateCopy(string path, Dataset src, int strict, string[] options, Gdal.GDALProgressFuncDelegate callback, string callback_data) {
    IntPtr temppath = GdalPINVOKE.StringToUtf8Unmanaged(path);
    using (var tempoptions = new GdalPINVOKE.StringListMarshal(options)) { 
    IntPtr tempcallback_data = GdalPINVOKE.StringToUtf8Unmanaged(callback_data);
    try {
      IntPtr cPtr = GdalPINVOKE.Driver_CreateCopy(swigCPtr, temppath, Dataset.getCPtr(src), strict, tempoptions._ar, callback, tempcallback_data);
      Dataset ret = (cPtr == IntPtr.Zero) ? null : new Dataset(cPtr, true, ThisOwn_true());
      if (GdalPINVOKE.SWIGPendingException.Pending) throw GdalPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } finally {
    System.Runtime.InteropServices.Marshal.FreeHGlobal(temppath);
    System.Runtime.InteropServices.Marshal.FreeHGlobal(tempcallback_data);
    }
    }
  }

  public CPLErr Delete(string path) {
    IntPtr temppath = GdalPINVOKE.StringToUtf8Unmanaged(path);
    try {
      CPLErr ret = (CPLErr)GdalPINVOKE.Driver_Delete(swigCPtr, temppath);
      if (GdalPINVOKE.SWIGPendingException.Pending) throw GdalPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } finally {
    System.Runtime.InteropServices.Marshal.FreeHGlobal(temppath);
    }
  }

  public CPLErr Rename(string newName, string oldName) {
    IntPtr tempnewName = GdalPINVOKE.StringToUtf8Unmanaged(newName);
    IntPtr tempoldName = GdalPINVOKE.StringToUtf8Unmanaged(oldName);
    try {
      CPLErr ret = (CPLErr)GdalPINVOKE.Driver_Rename(swigCPtr, tempnewName, tempoldName);
      if (GdalPINVOKE.SWIGPendingException.Pending) throw GdalPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } finally {
    System.Runtime.InteropServices.Marshal.FreeHGlobal(tempnewName);
    System.Runtime.InteropServices.Marshal.FreeHGlobal(tempoldName);
    }
  }

  public CPLErr CopyFiles(string newName, string oldName) {
    IntPtr tempnewName = GdalPINVOKE.StringToUtf8Unmanaged(newName);
    IntPtr tempoldName = GdalPINVOKE.StringToUtf8Unmanaged(oldName);
    try {
      CPLErr ret = (CPLErr)GdalPINVOKE.Driver_CopyFiles(swigCPtr, tempnewName, tempoldName);
      if (GdalPINVOKE.SWIGPendingException.Pending) throw GdalPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } finally {
    System.Runtime.InteropServices.Marshal.FreeHGlobal(tempnewName);
    System.Runtime.InteropServices.Marshal.FreeHGlobal(tempoldName);
    }
  }

  public bool HasOpenOption(string openOptionName) {
    IntPtr tempopenOptionName = GdalPINVOKE.StringToUtf8Unmanaged(openOptionName);
    try {
      bool ret = GdalPINVOKE.Driver_HasOpenOption(swigCPtr, tempopenOptionName);
      if (GdalPINVOKE.SWIGPendingException.Pending) throw GdalPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } finally {
    System.Runtime.InteropServices.Marshal.FreeHGlobal(tempopenOptionName);
    }
  }

  public int Register() {
    int ret = GdalPINVOKE.Driver_Register(swigCPtr);
    if (GdalPINVOKE.SWIGPendingException.Pending) throw GdalPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Deregister() {
    GdalPINVOKE.Driver_Deregister(swigCPtr);
    if (GdalPINVOKE.SWIGPendingException.Pending) throw GdalPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
