//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace OSGeo.GDAL {

public enum ExtendedDataTypeClass {
  GEDTC_NUMERIC,
  GEDTC_STRING,
  GEDTC_COMPOUND
}

}
