//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace OSGeo.GDAL {

using global::System;
using global::System.Runtime.InteropServices;

public class Group : global::System.IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;
  protected object swigParentRef;

  protected static object ThisOwn_true() { return null; }
  protected object ThisOwn_false() { return this; }

  public Group(IntPtr cPtr, bool cMemoryOwn, object parent) {
    swigCMemOwn = cMemoryOwn;
    swigParentRef = parent;
    swigCPtr = new HandleRef(this, cPtr);
  }

  public static HandleRef getCPtr(Group obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }
  public static HandleRef getCPtrAndDisown(Group obj, object parent) {
    if (obj != null)
    {
      obj.swigCMemOwn = false;
      obj.swigParentRef = parent;
      return obj.swigCPtr;
    }
    else
    {
      return new HandleRef(null, IntPtr.Zero);
    }
  }
  public static HandleRef getCPtrAndSetReference(Group obj, object parent) {
    if (obj != null)
    {
      obj.swigParentRef = parent;
      return obj.swigCPtr;
    }
    else
    {
      return new HandleRef(null, IntPtr.Zero);
    }
  }

  ~Group() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          GdalPINVOKE.delete_Group(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public string GetName() {
  /* %typemap(csout) (char *), (char *&), (char[ANY]), (char[]), (const char *utf8_string) */
  IntPtr cPtr = GdalPINVOKE.Group_GetName(swigCPtr);
  string ret = GdalPINVOKE.LengthPrefixedUtf16UnmanagedToString(cPtr);
  
    if (GdalPINVOKE.SWIGPendingException.Pending) throw GdalPINVOKE.SWIGPendingException.Retrieve();
  return ret;
}

  public string GetFullName() {
  /* %typemap(csout) (char *), (char *&), (char[ANY]), (char[]), (const char *utf8_string) */
  IntPtr cPtr = GdalPINVOKE.Group_GetFullName(swigCPtr);
  string ret = GdalPINVOKE.LengthPrefixedUtf16UnmanagedToString(cPtr);
  
    if (GdalPINVOKE.SWIGPendingException.Pending) throw GdalPINVOKE.SWIGPendingException.Retrieve();
  return ret;
}

  public string[] GetMDArrayNames(string[] options) {
    using (var tempoptions = new GdalPINVOKE.StringListMarshal(options)) { 
    {
    /* %typemap(csout) char** CSL, char **dictAndCSLDestroy */
    /*@SWIG:C:/Users/runes/miniconda3/conda-bld/gdal-csharp_1779183890733/work/swig/include/csharp\csharp_strings.i,304,CS_MARSHAL_STRING_LIST@*/
    IntPtr cPtr = GdalPINVOKE.Group_GetMDArrayNames(swigCPtr, tempoptions._ar);
    IntPtr objPtr;
    int count = 0;
    if (cPtr != IntPtr.Zero) {
      while (System.Runtime.InteropServices.Marshal.ReadIntPtr(cPtr, count*IntPtr.Size) != IntPtr.Zero)
        ++count;
    }
    string[] ret = new string[count];
    if (count > 0) {
      for(int cx = 0; cx < count; cx++) {
        objPtr = System.Runtime.InteropServices.Marshal.ReadIntPtr(cPtr, cx * System.Runtime.InteropServices.Marshal.SizeOf(typeof(IntPtr)));
        ret[cx]= (objPtr == IntPtr.Zero) ? null : Gdal.Utf8BytesToString(objPtr);
      }
    }
/*@SWIG@*/
    if (cPtr != IntPtr.Zero)
      GdalPINVOKE.StringListDestroy(cPtr);
    
      if (GdalPINVOKE.SWIGPendingException.Pending) throw GdalPINVOKE.SWIGPendingException.Retrieve();
    return ret;
}
    }
  }

  public string[] GetMDArrayFullNamesRecursive(string[] groupOptions, string[] arrayOptions) {
    using (var tempgroupOptions = new GdalPINVOKE.StringListMarshal(groupOptions)) { 
    using (var temparrayOptions = new GdalPINVOKE.StringListMarshal(arrayOptions)) { 
    {
    /* %typemap(csout) char** CSL, char **dictAndCSLDestroy */
    /*@SWIG:C:/Users/runes/miniconda3/conda-bld/gdal-csharp_1779183890733/work/swig/include/csharp\csharp_strings.i,304,CS_MARSHAL_STRING_LIST@*/
    IntPtr cPtr = GdalPINVOKE.Group_GetMDArrayFullNamesRecursive(swigCPtr, tempgroupOptions._ar, temparrayOptions._ar);
    IntPtr objPtr;
    int count = 0;
    if (cPtr != IntPtr.Zero) {
      while (System.Runtime.InteropServices.Marshal.ReadIntPtr(cPtr, count*IntPtr.Size) != IntPtr.Zero)
        ++count;
    }
    string[] ret = new string[count];
    if (count > 0) {
      for(int cx = 0; cx < count; cx++) {
        objPtr = System.Runtime.InteropServices.Marshal.ReadIntPtr(cPtr, cx * System.Runtime.InteropServices.Marshal.SizeOf(typeof(IntPtr)));
        ret[cx]= (objPtr == IntPtr.Zero) ? null : Gdal.Utf8BytesToString(objPtr);
      }
    }
/*@SWIG@*/
    if (cPtr != IntPtr.Zero)
      GdalPINVOKE.StringListDestroy(cPtr);
    
      if (GdalPINVOKE.SWIGPendingException.Pending) throw GdalPINVOKE.SWIGPendingException.Retrieve();
    return ret;
}
    }
    }
  }

  public MDArray OpenMDArray(string name, string[] options) {
    IntPtr tempname = GdalPINVOKE.StringToUtf8Unmanaged(name);
    using (var tempoptions = new GdalPINVOKE.StringListMarshal(options)) { 
    try {
      IntPtr cPtr = GdalPINVOKE.Group_OpenMDArray(swigCPtr, tempname, tempoptions._ar);
      MDArray ret = (cPtr == IntPtr.Zero) ? null : new MDArray(cPtr, true, ThisOwn_true());
      if (GdalPINVOKE.SWIGPendingException.Pending) throw GdalPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } finally {
    System.Runtime.InteropServices.Marshal.FreeHGlobal(tempname);
    }
    }
  }

  public MDArray OpenMDArrayFromFullname(string name, string[] options) {
    IntPtr tempname = GdalPINVOKE.StringToUtf8Unmanaged(name);
    using (var tempoptions = new GdalPINVOKE.StringListMarshal(options)) { 
    try {
      IntPtr cPtr = GdalPINVOKE.Group_OpenMDArrayFromFullname(swigCPtr, tempname, tempoptions._ar);
      MDArray ret = (cPtr == IntPtr.Zero) ? null : new MDArray(cPtr, true, ThisOwn_true());
      if (GdalPINVOKE.SWIGPendingException.Pending) throw GdalPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } finally {
    System.Runtime.InteropServices.Marshal.FreeHGlobal(tempname);
    }
    }
  }

  public MDArray ResolveMDArray(string name, string starting_point, string[] options) {
    IntPtr tempname = GdalPINVOKE.StringToUtf8Unmanaged(name);
    IntPtr tempstarting_point = GdalPINVOKE.StringToUtf8Unmanaged(starting_point);
    using (var tempoptions = new GdalPINVOKE.StringListMarshal(options)) { 
    try {
      IntPtr cPtr = GdalPINVOKE.Group_ResolveMDArray(swigCPtr, tempname, tempstarting_point, tempoptions._ar);
      MDArray ret = (cPtr == IntPtr.Zero) ? null : new MDArray(cPtr, true, ThisOwn_true());
      if (GdalPINVOKE.SWIGPendingException.Pending) throw GdalPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } finally {
    System.Runtime.InteropServices.Marshal.FreeHGlobal(tempname);
    System.Runtime.InteropServices.Marshal.FreeHGlobal(tempstarting_point);
    }
    }
  }

  public string[] GetGroupNames(string[] options) {
    using (var tempoptions = new GdalPINVOKE.StringListMarshal(options)) { 
    {
    /* %typemap(csout) char** CSL, char **dictAndCSLDestroy */
    /*@SWIG:C:/Users/runes/miniconda3/conda-bld/gdal-csharp_1779183890733/work/swig/include/csharp\csharp_strings.i,304,CS_MARSHAL_STRING_LIST@*/
    IntPtr cPtr = GdalPINVOKE.Group_GetGroupNames(swigCPtr, tempoptions._ar);
    IntPtr objPtr;
    int count = 0;
    if (cPtr != IntPtr.Zero) {
      while (System.Runtime.InteropServices.Marshal.ReadIntPtr(cPtr, count*IntPtr.Size) != IntPtr.Zero)
        ++count;
    }
    string[] ret = new string[count];
    if (count > 0) {
      for(int cx = 0; cx < count; cx++) {
        objPtr = System.Runtime.InteropServices.Marshal.ReadIntPtr(cPtr, cx * System.Runtime.InteropServices.Marshal.SizeOf(typeof(IntPtr)));
        ret[cx]= (objPtr == IntPtr.Zero) ? null : Gdal.Utf8BytesToString(objPtr);
      }
    }
/*@SWIG@*/
    if (cPtr != IntPtr.Zero)
      GdalPINVOKE.StringListDestroy(cPtr);
    
      if (GdalPINVOKE.SWIGPendingException.Pending) throw GdalPINVOKE.SWIGPendingException.Retrieve();
    return ret;
}
    }
  }

  public Group OpenGroup(string name, string[] options) {
    IntPtr tempname = GdalPINVOKE.StringToUtf8Unmanaged(name);
    using (var tempoptions = new GdalPINVOKE.StringListMarshal(options)) { 
    try {
      IntPtr cPtr = GdalPINVOKE.Group_OpenGroup(swigCPtr, tempname, tempoptions._ar);
      Group ret = (cPtr == IntPtr.Zero) ? null : new Group(cPtr, true, ThisOwn_true());
      if (GdalPINVOKE.SWIGPendingException.Pending) throw GdalPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } finally {
    System.Runtime.InteropServices.Marshal.FreeHGlobal(tempname);
    }
    }
  }

  public Group OpenGroupFromFullname(string name, string[] options) {
    IntPtr tempname = GdalPINVOKE.StringToUtf8Unmanaged(name);
    using (var tempoptions = new GdalPINVOKE.StringListMarshal(options)) { 
    try {
      IntPtr cPtr = GdalPINVOKE.Group_OpenGroupFromFullname(swigCPtr, tempname, tempoptions._ar);
      Group ret = (cPtr == IntPtr.Zero) ? null : new Group(cPtr, true, ThisOwn_true());
      if (GdalPINVOKE.SWIGPendingException.Pending) throw GdalPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } finally {
    System.Runtime.InteropServices.Marshal.FreeHGlobal(tempname);
    }
    }
  }

  public string[] GetVectorLayerNames(string[] options) {
    using (var tempoptions = new GdalPINVOKE.StringListMarshal(options)) { 
    {
    /* %typemap(csout) char** CSL, char **dictAndCSLDestroy */
    /*@SWIG:C:/Users/runes/miniconda3/conda-bld/gdal-csharp_1779183890733/work/swig/include/csharp\csharp_strings.i,304,CS_MARSHAL_STRING_LIST@*/
    IntPtr cPtr = GdalPINVOKE.Group_GetVectorLayerNames(swigCPtr, tempoptions._ar);
    IntPtr objPtr;
    int count = 0;
    if (cPtr != IntPtr.Zero) {
      while (System.Runtime.InteropServices.Marshal.ReadIntPtr(cPtr, count*IntPtr.Size) != IntPtr.Zero)
        ++count;
    }
    string[] ret = new string[count];
    if (count > 0) {
      for(int cx = 0; cx < count; cx++) {
        objPtr = System.Runtime.InteropServices.Marshal.ReadIntPtr(cPtr, cx * System.Runtime.InteropServices.Marshal.SizeOf(typeof(IntPtr)));
        ret[cx]= (objPtr == IntPtr.Zero) ? null : Gdal.Utf8BytesToString(objPtr);
      }
    }
/*@SWIG@*/
    if (cPtr != IntPtr.Zero)
      GdalPINVOKE.StringListDestroy(cPtr);
    
      if (GdalPINVOKE.SWIGPendingException.Pending) throw GdalPINVOKE.SWIGPendingException.Retrieve();
    return ret;
}
    }
  }

  public OSGeo.OGR.Layer OpenVectorLayer(string name, string[] options) {
    IntPtr tempname = GdalPINVOKE.StringToUtf8Unmanaged(name);
    using (var tempoptions = new GdalPINVOKE.StringListMarshal(options)) { 
    try {
      IntPtr cPtr = GdalPINVOKE.Group_OpenVectorLayer(swigCPtr, tempname, tempoptions._ar);
      OSGeo.OGR.Layer ret = (cPtr == IntPtr.Zero) ? null : new OSGeo.OGR.Layer(cPtr, false, ThisOwn_false());
      if (GdalPINVOKE.SWIGPendingException.Pending) throw GdalPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } finally {
    System.Runtime.InteropServices.Marshal.FreeHGlobal(tempname);
    }
    }
  }

  public Attribute GetAttribute(string name) {
    IntPtr tempname = GdalPINVOKE.StringToUtf8Unmanaged(name);
    try {
      IntPtr cPtr = GdalPINVOKE.Group_GetAttribute(swigCPtr, tempname);
      Attribute ret = (cPtr == IntPtr.Zero) ? null : new Attribute(cPtr, true, ThisOwn_true());
      if (GdalPINVOKE.SWIGPendingException.Pending) throw GdalPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } finally {
    System.Runtime.InteropServices.Marshal.FreeHGlobal(tempname);
    }
  }

  public string[] GetStructuralInfo() {
  /* %typemap(csout) char**options, char **dict */
  /*@SWIG:C:/Users/runes/miniconda3/conda-bld/gdal-csharp_1779183890733/work/swig/include/csharp\csharp_strings.i,304,CS_MARSHAL_STRING_LIST@*/
  IntPtr cPtr = GdalPINVOKE.Group_GetStructuralInfo(swigCPtr);
  IntPtr objPtr;
  int count = 0;
  if (cPtr != IntPtr.Zero) {
    while (System.Runtime.InteropServices.Marshal.ReadIntPtr(cPtr, count*IntPtr.Size) != IntPtr.Zero)
      ++count;
  }
  string[] ret = new string[count];
  if (count > 0) {
    for(int cx = 0; cx < count; cx++) {
      objPtr = System.Runtime.InteropServices.Marshal.ReadIntPtr(cPtr, cx * System.Runtime.InteropServices.Marshal.SizeOf(typeof(IntPtr)));
      ret[cx]= (objPtr == IntPtr.Zero) ? null : Gdal.Utf8BytesToString(objPtr);
    }
  }
/*@SWIG@*/
  
    if (GdalPINVOKE.SWIGPendingException.Pending) throw GdalPINVOKE.SWIGPendingException.Retrieve();
  return ret;
}

  public Group CreateGroup(string name, string[] options) {
    IntPtr tempname = GdalPINVOKE.StringToUtf8Unmanaged(name);
    using (var tempoptions = new GdalPINVOKE.StringListMarshal(options)) { 
    try {
      IntPtr cPtr = GdalPINVOKE.Group_CreateGroup(swigCPtr, tempname, tempoptions._ar);
      Group ret = (cPtr == IntPtr.Zero) ? null : new Group(cPtr, true, ThisOwn_true());
      if (GdalPINVOKE.SWIGPendingException.Pending) throw GdalPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } finally {
    System.Runtime.InteropServices.Marshal.FreeHGlobal(tempname);
    }
    }
  }

  public CPLErr DeleteGroup(string name, string[] options) {
    IntPtr tempname = GdalPINVOKE.StringToUtf8Unmanaged(name);
    using (var tempoptions = new GdalPINVOKE.StringListMarshal(options)) { 
    try {
      CPLErr ret = (CPLErr)GdalPINVOKE.Group_DeleteGroup(swigCPtr, tempname, tempoptions._ar);
      if (GdalPINVOKE.SWIGPendingException.Pending) throw GdalPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } finally {
    System.Runtime.InteropServices.Marshal.FreeHGlobal(tempname);
    }
    }
  }

  public Dimension CreateDimension(string name, string dim_type, string direction, ulong size, string[] options) {
    IntPtr tempname = GdalPINVOKE.StringToUtf8Unmanaged(name);
    IntPtr tempdim_type = GdalPINVOKE.StringToUtf8Unmanaged(dim_type);
    IntPtr tempdirection = GdalPINVOKE.StringToUtf8Unmanaged(direction);
    using (var tempoptions = new GdalPINVOKE.StringListMarshal(options)) { 
    try {
      IntPtr cPtr = GdalPINVOKE.Group_CreateDimension(swigCPtr, tempname, tempdim_type, tempdirection, size, tempoptions._ar);
      Dimension ret = (cPtr == IntPtr.Zero) ? null : new Dimension(cPtr, true, ThisOwn_true());
      if (GdalPINVOKE.SWIGPendingException.Pending) throw GdalPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } finally {
    System.Runtime.InteropServices.Marshal.FreeHGlobal(tempname);
    System.Runtime.InteropServices.Marshal.FreeHGlobal(tempdim_type);
    System.Runtime.InteropServices.Marshal.FreeHGlobal(tempdirection);
    }
    }
  }

  public CPLErr DeleteMDArray(string name, string[] options) {
    IntPtr tempname = GdalPINVOKE.StringToUtf8Unmanaged(name);
    using (var tempoptions = new GdalPINVOKE.StringListMarshal(options)) { 
    try {
      CPLErr ret = (CPLErr)GdalPINVOKE.Group_DeleteMDArray(swigCPtr, tempname, tempoptions._ar);
      if (GdalPINVOKE.SWIGPendingException.Pending) throw GdalPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } finally {
    System.Runtime.InteropServices.Marshal.FreeHGlobal(tempname);
    }
    }
  }

  public Attribute CreateAttribute(string name, int dimensions, uint[] sizes, ExtendedDataType data_type, string[] options) {
    IntPtr tempname = GdalPINVOKE.StringToUtf8Unmanaged(name);
    GCHandle swig_handleTo_sizes = GCHandle.Alloc(sizes, GCHandleType.Pinned);
    try {
    using (var tempoptions = new GdalPINVOKE.StringListMarshal(options)) { 
    try {
      IntPtr cPtr = GdalPINVOKE.Group_CreateAttribute(swigCPtr, tempname, dimensions, swig_handleTo_sizes.AddrOfPinnedObject(), ExtendedDataType.getCPtr(data_type), tempoptions._ar);
      Attribute ret = (cPtr == IntPtr.Zero) ? null : new Attribute(cPtr, true, ThisOwn_true());
      if (GdalPINVOKE.SWIGPendingException.Pending) throw GdalPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } finally {
    System.Runtime.InteropServices.Marshal.FreeHGlobal(tempname);
    }
    }
    } finally {
        swig_handleTo_sizes.Free();
        GC.KeepAlive(this);
    }
  }

  public CPLErr DeleteAttribute(string name, string[] options) {
    IntPtr tempname = GdalPINVOKE.StringToUtf8Unmanaged(name);
    using (var tempoptions = new GdalPINVOKE.StringListMarshal(options)) { 
    try {
      CPLErr ret = (CPLErr)GdalPINVOKE.Group_DeleteAttribute(swigCPtr, tempname, tempoptions._ar);
      if (GdalPINVOKE.SWIGPendingException.Pending) throw GdalPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } finally {
    System.Runtime.InteropServices.Marshal.FreeHGlobal(tempname);
    }
    }
  }

  public CPLErr Rename(string newName) {
    IntPtr tempnewName = GdalPINVOKE.StringToUtf8Unmanaged(newName);
    try {
      CPLErr ret = (CPLErr)GdalPINVOKE.Group_Rename(swigCPtr, tempnewName);
      if (GdalPINVOKE.SWIGPendingException.Pending) throw GdalPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } finally {
    System.Runtime.InteropServices.Marshal.FreeHGlobal(tempnewName);
    }
  }

  public Group SubsetDimensionFromSelection(string selection, string[] options) {
    IntPtr tempselection = GdalPINVOKE.StringToUtf8Unmanaged(selection);
    using (var tempoptions = new GdalPINVOKE.StringListMarshal(options)) { 
    try {
      IntPtr cPtr = GdalPINVOKE.Group_SubsetDimensionFromSelection(swigCPtr, tempselection, tempoptions._ar);
      Group ret = (cPtr == IntPtr.Zero) ? null : new Group(cPtr, true, ThisOwn_true());
      if (GdalPINVOKE.SWIGPendingException.Pending) throw GdalPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } finally {
    System.Runtime.InteropServices.Marshal.FreeHGlobal(tempselection);
    }
    }
  }

  public uint GetDataTypeCount() {
    uint ret = GdalPINVOKE.Group_GetDataTypeCount(swigCPtr);
    if (GdalPINVOKE.SWIGPendingException.Pending) throw GdalPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public ExtendedDataType GetDataType(uint idx) {
    IntPtr cPtr = GdalPINVOKE.Group_GetDataType(swigCPtr, idx);
    ExtendedDataType ret = (cPtr == IntPtr.Zero) ? null : new ExtendedDataType(cPtr, true, ThisOwn_true());
    if (GdalPINVOKE.SWIGPendingException.Pending) throw GdalPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
