//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace OSGeo.GDAL {

using global::System;
using global::System.Runtime.InteropServices;

public class MajorObject : global::System.IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;
  protected object swigParentRef;

  protected static object ThisOwn_true() { return null; }
  protected object ThisOwn_false() { return this; }

  public MajorObject(IntPtr cPtr, bool cMemoryOwn, object parent) {
    swigCMemOwn = cMemoryOwn;
    swigParentRef = parent;
    swigCPtr = new HandleRef(this, cPtr);
  }

  public static HandleRef getCPtr(MajorObject obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }
  public static HandleRef getCPtrAndDisown(MajorObject obj, object parent) {
    if (obj != null)
    {
      obj.swigCMemOwn = false;
      obj.swigParentRef = parent;
      return obj.swigCPtr;
    }
    else
    {
      return new HandleRef(null, IntPtr.Zero);
    }
  }
  public static HandleRef getCPtrAndSetReference(MajorObject obj, object parent) {
    if (obj != null)
    {
      obj.swigParentRef = parent;
      return obj.swigCPtr;
    }
    else
    {
      return new HandleRef(null, IntPtr.Zero);
    }
  }

  ~MajorObject() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          throw new global::System.MethodAccessException("C++ destructor does not have public access");
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public string GetDescription() {
  /* %typemap(csout) (char *), (char *&), (char[ANY]), (char[]), (const char *utf8_string) */
  IntPtr cPtr = GdalPINVOKE.MajorObject_GetDescription(swigCPtr);
  string ret = GdalPINVOKE.LengthPrefixedUtf16UnmanagedToString(cPtr);
  
    if (GdalPINVOKE.SWIGPendingException.Pending) throw GdalPINVOKE.SWIGPendingException.Retrieve();
  return ret;
}

  public void SetDescription(string pszNewDesc) {
    IntPtr temppszNewDesc = GdalPINVOKE.StringToUtf8Unmanaged(pszNewDesc);
    try {
      GdalPINVOKE.MajorObject_SetDescription(swigCPtr, temppszNewDesc);
      if (GdalPINVOKE.SWIGPendingException.Pending) throw GdalPINVOKE.SWIGPendingException.Retrieve();
    } finally {
    System.Runtime.InteropServices.Marshal.FreeHGlobal(temppszNewDesc);
    }
  }

  public string[] GetMetadataDomainList() {
  /* %typemap(csout) char** CSL, char **dictAndCSLDestroy */
  /*@SWIG:C:/Users/runes/miniconda3/conda-bld/gdal-csharp_1779183890733/work/swig/include/csharp\csharp_strings.i,304,CS_MARSHAL_STRING_LIST@*/
  IntPtr cPtr = GdalPINVOKE.MajorObject_GetMetadataDomainList(swigCPtr);
  IntPtr objPtr;
  int count = 0;
  if (cPtr != IntPtr.Zero) {
    while (System.Runtime.InteropServices.Marshal.ReadIntPtr(cPtr, count*IntPtr.Size) != IntPtr.Zero)
      ++count;
  }
  string[] ret = new string[count];
  if (count > 0) {
    for(int cx = 0; cx < count; cx++) {
      objPtr = System.Runtime.InteropServices.Marshal.ReadIntPtr(cPtr, cx * System.Runtime.InteropServices.Marshal.SizeOf(typeof(IntPtr)));
      ret[cx]= (objPtr == IntPtr.Zero) ? null : Gdal.Utf8BytesToString(objPtr);
    }
  }
/*@SWIG@*/
  if (cPtr != IntPtr.Zero)
    GdalPINVOKE.StringListDestroy(cPtr);
  
    if (GdalPINVOKE.SWIGPendingException.Pending) throw GdalPINVOKE.SWIGPendingException.Retrieve();
  return ret;
}

  public string[] GetMetadata(string pszDomain) {
    IntPtr temppszDomain = GdalPINVOKE.StringToUtf8Unmanaged(pszDomain);
    try {
    /* %typemap(csout) char**options, char **dict */
    /*@SWIG:C:/Users/runes/miniconda3/conda-bld/gdal-csharp_1779183890733/work/swig/include/csharp\csharp_strings.i,304,CS_MARSHAL_STRING_LIST@*/
    IntPtr cPtr = GdalPINVOKE.MajorObject_GetMetadata(swigCPtr, temppszDomain);
    IntPtr objPtr;
    int count = 0;
    if (cPtr != IntPtr.Zero) {
      while (System.Runtime.InteropServices.Marshal.ReadIntPtr(cPtr, count*IntPtr.Size) != IntPtr.Zero)
        ++count;
    }
    string[] ret = new string[count];
    if (count > 0) {
      for(int cx = 0; cx < count; cx++) {
        objPtr = System.Runtime.InteropServices.Marshal.ReadIntPtr(cPtr, cx * System.Runtime.InteropServices.Marshal.SizeOf(typeof(IntPtr)));
        ret[cx]= (objPtr == IntPtr.Zero) ? null : Gdal.Utf8BytesToString(objPtr);
      }
    }
/*@SWIG@*/
    
      if (GdalPINVOKE.SWIGPendingException.Pending) throw GdalPINVOKE.SWIGPendingException.Retrieve();
    return ret;
} finally {
    System.Runtime.InteropServices.Marshal.FreeHGlobal(temppszDomain);
    }
  }

  public CPLErr SetMetadata(string[] papszMetadata, string pszDomain) {
    using (var temppapszMetadata = new GdalPINVOKE.StringListMarshal(papszMetadata)) { 
    IntPtr temppszDomain = GdalPINVOKE.StringToUtf8Unmanaged(pszDomain);
    try {
      CPLErr ret = (CPLErr)GdalPINVOKE.MajorObject_SetMetadata__SWIG_0(swigCPtr, temppapszMetadata._ar, temppszDomain);
      if (GdalPINVOKE.SWIGPendingException.Pending) throw GdalPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } finally {
    System.Runtime.InteropServices.Marshal.FreeHGlobal(temppszDomain);
    }
    }
  }

  public CPLErr SetMetadata(string pszMetadataString, string pszDomain) {
    IntPtr temppszMetadataString = GdalPINVOKE.StringToUtf8Unmanaged(pszMetadataString);
    IntPtr temppszDomain = GdalPINVOKE.StringToUtf8Unmanaged(pszDomain);
    try {
      CPLErr ret = (CPLErr)GdalPINVOKE.MajorObject_SetMetadata__SWIG_1(swigCPtr, temppszMetadataString, temppszDomain);
      if (GdalPINVOKE.SWIGPendingException.Pending) throw GdalPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } finally {
    System.Runtime.InteropServices.Marshal.FreeHGlobal(temppszMetadataString);
    System.Runtime.InteropServices.Marshal.FreeHGlobal(temppszDomain);
    }
  }

  public string GetMetadataItem(string pszName, string pszDomain) {
    IntPtr temppszName = GdalPINVOKE.StringToUtf8Unmanaged(pszName);
    IntPtr temppszDomain = GdalPINVOKE.StringToUtf8Unmanaged(pszDomain);
    try {
    /* %typemap(csout) (char *), (char *&), (char[ANY]), (char[]), (const char *utf8_string) */
    IntPtr cPtr = GdalPINVOKE.MajorObject_GetMetadataItem(swigCPtr, temppszName, temppszDomain);
    string ret = GdalPINVOKE.LengthPrefixedUtf16UnmanagedToString(cPtr);
    
      if (GdalPINVOKE.SWIGPendingException.Pending) throw GdalPINVOKE.SWIGPendingException.Retrieve();
    return ret;
} finally {
    System.Runtime.InteropServices.Marshal.FreeHGlobal(temppszName);
    System.Runtime.InteropServices.Marshal.FreeHGlobal(temppszDomain);
    }
  }

  public CPLErr SetMetadataItem(string pszName, string pszValue, string pszDomain) {
    IntPtr temppszName = GdalPINVOKE.StringToUtf8Unmanaged(pszName);
    IntPtr temppszValue = GdalPINVOKE.StringToUtf8Unmanaged(pszValue);
    IntPtr temppszDomain = GdalPINVOKE.StringToUtf8Unmanaged(pszDomain);
    try {
      CPLErr ret = (CPLErr)GdalPINVOKE.MajorObject_SetMetadataItem(swigCPtr, temppszName, temppszValue, temppszDomain);
      if (GdalPINVOKE.SWIGPendingException.Pending) throw GdalPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } finally {
    System.Runtime.InteropServices.Marshal.FreeHGlobal(temppszName);
    System.Runtime.InteropServices.Marshal.FreeHGlobal(temppszValue);
    System.Runtime.InteropServices.Marshal.FreeHGlobal(temppszDomain);
    }
  }

}

}
