//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace OSGeo.GDAL {

using global::System;
using global::System.Runtime.InteropServices;

public class MDArray : global::System.IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;
  protected object swigParentRef;

  protected static object ThisOwn_true() { return null; }
  protected object ThisOwn_false() { return this; }

  public MDArray(IntPtr cPtr, bool cMemoryOwn, object parent) {
    swigCMemOwn = cMemoryOwn;
    swigParentRef = parent;
    swigCPtr = new HandleRef(this, cPtr);
  }

  public static HandleRef getCPtr(MDArray obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }
  public static HandleRef getCPtrAndDisown(MDArray obj, object parent) {
    if (obj != null)
    {
      obj.swigCMemOwn = false;
      obj.swigParentRef = parent;
      return obj.swigCPtr;
    }
    else
    {
      return new HandleRef(null, IntPtr.Zero);
    }
  }
  public static HandleRef getCPtrAndSetReference(MDArray obj, object parent) {
    if (obj != null)
    {
      obj.swigParentRef = parent;
      return obj.swigCPtr;
    }
    else
    {
      return new HandleRef(null, IntPtr.Zero);
    }
  }

  ~MDArray() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          GdalPINVOKE.delete_MDArray(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public string GetName() {
  /* %typemap(csout) (char *), (char *&), (char[ANY]), (char[]), (const char *utf8_string) */
  IntPtr cPtr = GdalPINVOKE.MDArray_GetName(swigCPtr);
  string ret = GdalPINVOKE.LengthPrefixedUtf16UnmanagedToString(cPtr);
  
    if (GdalPINVOKE.SWIGPendingException.Pending) throw GdalPINVOKE.SWIGPendingException.Retrieve();
  return ret;
}

  public string GetFullName() {
  /* %typemap(csout) (char *), (char *&), (char[ANY]), (char[]), (const char *utf8_string) */
  IntPtr cPtr = GdalPINVOKE.MDArray_GetFullName(swigCPtr);
  string ret = GdalPINVOKE.LengthPrefixedUtf16UnmanagedToString(cPtr);
  
    if (GdalPINVOKE.SWIGPendingException.Pending) throw GdalPINVOKE.SWIGPendingException.Retrieve();
  return ret;
}

  public ulong GetTotalElementsCount() {
    ulong res = GdalPINVOKE.MDArray_GetTotalElementsCount(swigCPtr);
    if (GdalPINVOKE.SWIGPendingException.Pending) throw GdalPINVOKE.SWIGPendingException.Retrieve();
    return res;
}

  public uint GetDimensionCount() {
    uint ret = GdalPINVOKE.MDArray_GetDimensionCount(swigCPtr);
    if (GdalPINVOKE.SWIGPendingException.Pending) throw GdalPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public ExtendedDataType GetDataType() {
    IntPtr cPtr = GdalPINVOKE.MDArray_GetDataType(swigCPtr);
    ExtendedDataType ret = (cPtr == IntPtr.Zero) ? null : new ExtendedDataType(cPtr, true, ThisOwn_true());
    if (GdalPINVOKE.SWIGPendingException.Pending) throw GdalPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string[] GetStructuralInfo() {
  /* %typemap(csout) char**options, char **dict */
  /*@SWIG:C:/Users/runes/miniconda3/conda-bld/gdal-csharp_1779183890733/work/swig/include/csharp\csharp_strings.i,304,CS_MARSHAL_STRING_LIST@*/
  IntPtr cPtr = GdalPINVOKE.MDArray_GetStructuralInfo(swigCPtr);
  IntPtr objPtr;
  int count = 0;
  if (cPtr != IntPtr.Zero) {
    while (System.Runtime.InteropServices.Marshal.ReadIntPtr(cPtr, count*IntPtr.Size) != IntPtr.Zero)
      ++count;
  }
  string[] ret = new string[count];
  if (count > 0) {
    for(int cx = 0; cx < count; cx++) {
      objPtr = System.Runtime.InteropServices.Marshal.ReadIntPtr(cPtr, cx * System.Runtime.InteropServices.Marshal.SizeOf(typeof(IntPtr)));
      ret[cx]= (objPtr == IntPtr.Zero) ? null : Gdal.Utf8BytesToString(objPtr);
    }
  }
/*@SWIG@*/
  
    if (GdalPINVOKE.SWIGPendingException.Pending) throw GdalPINVOKE.SWIGPendingException.Retrieve();
  return ret;
}

  public CPLErr Resize(int newDimensions, uint[] newSizes, string[] options) {
    GCHandle swig_handleTo_newSizes = GCHandle.Alloc(newSizes, GCHandleType.Pinned);
    try {
    using (var tempoptions = new GdalPINVOKE.StringListMarshal(options)) { 
    {
      CPLErr ret = (CPLErr)GdalPINVOKE.MDArray_Resize(swigCPtr, newDimensions, swig_handleTo_newSizes.AddrOfPinnedObject(), tempoptions._ar);
      if (GdalPINVOKE.SWIGPendingException.Pending) throw GdalPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    }
    }
    } finally {
        swig_handleTo_newSizes.Free();
        GC.KeepAlive(this);
    }
  }

  public Attribute GetAttribute(string name) {
    IntPtr tempname = GdalPINVOKE.StringToUtf8Unmanaged(name);
    try {
      IntPtr cPtr = GdalPINVOKE.MDArray_GetAttribute(swigCPtr, tempname);
      Attribute ret = (cPtr == IntPtr.Zero) ? null : new Attribute(cPtr, true, ThisOwn_true());
      if (GdalPINVOKE.SWIGPendingException.Pending) throw GdalPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } finally {
    System.Runtime.InteropServices.Marshal.FreeHGlobal(tempname);
    }
  }

  public Attribute CreateAttribute(string name, int dimensions, uint[] sizes, ExtendedDataType data_type, string[] options) {
    IntPtr tempname = GdalPINVOKE.StringToUtf8Unmanaged(name);
    GCHandle swig_handleTo_sizes = GCHandle.Alloc(sizes, GCHandleType.Pinned);
    try {
    using (var tempoptions = new GdalPINVOKE.StringListMarshal(options)) { 
    try {
      IntPtr cPtr = GdalPINVOKE.MDArray_CreateAttribute(swigCPtr, tempname, dimensions, swig_handleTo_sizes.AddrOfPinnedObject(), ExtendedDataType.getCPtr(data_type), tempoptions._ar);
      Attribute ret = (cPtr == IntPtr.Zero) ? null : new Attribute(cPtr, true, ThisOwn_true());
      if (GdalPINVOKE.SWIGPendingException.Pending) throw GdalPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } finally {
    System.Runtime.InteropServices.Marshal.FreeHGlobal(tempname);
    }
    }
    } finally {
        swig_handleTo_sizes.Free();
        GC.KeepAlive(this);
    }
  }

  public CPLErr DeleteAttribute(string name, string[] options) {
    IntPtr tempname = GdalPINVOKE.StringToUtf8Unmanaged(name);
    using (var tempoptions = new GdalPINVOKE.StringListMarshal(options)) { 
    try {
      CPLErr ret = (CPLErr)GdalPINVOKE.MDArray_DeleteAttribute(swigCPtr, tempname, tempoptions._ar);
      if (GdalPINVOKE.SWIGPendingException.Pending) throw GdalPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } finally {
    System.Runtime.InteropServices.Marshal.FreeHGlobal(tempname);
    }
    }
  }

  public void GetNoDataValueAsDouble(out double val, out int hasval) {
    GdalPINVOKE.MDArray_GetNoDataValueAsDouble(swigCPtr, out val, out hasval);
    if (GdalPINVOKE.SWIGPendingException.Pending) throw GdalPINVOKE.SWIGPendingException.Retrieve();
  }

  public string GetNoDataValueAsString() {
  /* %typemap(csout) (char *), (char *&), (char[ANY]), (char[]), (const char *utf8_string) */
  IntPtr cPtr = GdalPINVOKE.MDArray_GetNoDataValueAsString(swigCPtr);
  string ret = GdalPINVOKE.LengthPrefixedUtf16UnmanagedToString(cPtr);
  
    if (GdalPINVOKE.SWIGPendingException.Pending) throw GdalPINVOKE.SWIGPendingException.Retrieve();
  return ret;
}

  public CPLErr SetNoDataValueDouble(double d) {
    CPLErr ret = (CPLErr)GdalPINVOKE.MDArray_SetNoDataValueDouble(swigCPtr, d);
    if (GdalPINVOKE.SWIGPendingException.Pending) throw GdalPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public CPLErr SetNoDataValueString(string nodata) {
    IntPtr tempnodata = GdalPINVOKE.StringToUtf8Unmanaged(nodata);
    try {
      CPLErr ret = (CPLErr)GdalPINVOKE.MDArray_SetNoDataValueString(swigCPtr, tempnodata);
      if (GdalPINVOKE.SWIGPendingException.Pending) throw GdalPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } finally {
    System.Runtime.InteropServices.Marshal.FreeHGlobal(tempnodata);
    }
  }

  public CPLErr DeleteNoDataValue() {
    CPLErr ret = (CPLErr)GdalPINVOKE.MDArray_DeleteNoDataValue(swigCPtr);
    if (GdalPINVOKE.SWIGPendingException.Pending) throw GdalPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void GetOffset(out double val, out int hasval) {
    GdalPINVOKE.MDArray_GetOffset(swigCPtr, out val, out hasval);
    if (GdalPINVOKE.SWIGPendingException.Pending) throw GdalPINVOKE.SWIGPendingException.Retrieve();
  }

  public DataType GetOffsetStorageType() {
    DataType ret = (DataType)GdalPINVOKE.MDArray_GetOffsetStorageType(swigCPtr);
    if (GdalPINVOKE.SWIGPendingException.Pending) throw GdalPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void GetScale(out double val, out int hasval) {
    GdalPINVOKE.MDArray_GetScale(swigCPtr, out val, out hasval);
    if (GdalPINVOKE.SWIGPendingException.Pending) throw GdalPINVOKE.SWIGPendingException.Retrieve();
  }

  public DataType GetScaleStorageType() {
    DataType ret = (DataType)GdalPINVOKE.MDArray_GetScaleStorageType(swigCPtr);
    if (GdalPINVOKE.SWIGPendingException.Pending) throw GdalPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public CPLErr SetOffset(double val, DataType storageType) {
    CPLErr ret = (CPLErr)GdalPINVOKE.MDArray_SetOffset(swigCPtr, val, (int)storageType);
    if (GdalPINVOKE.SWIGPendingException.Pending) throw GdalPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public CPLErr SetScale(double val, DataType storageType) {
    CPLErr ret = (CPLErr)GdalPINVOKE.MDArray_SetScale(swigCPtr, val, (int)storageType);
    if (GdalPINVOKE.SWIGPendingException.Pending) throw GdalPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public CPLErr SetUnit(string unit) {
    IntPtr tempunit = GdalPINVOKE.StringToUtf8Unmanaged(unit);
    try {
      CPLErr ret = (CPLErr)GdalPINVOKE.MDArray_SetUnit(swigCPtr, tempunit);
      if (GdalPINVOKE.SWIGPendingException.Pending) throw GdalPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } finally {
    System.Runtime.InteropServices.Marshal.FreeHGlobal(tempunit);
    }
  }

  public string GetUnit() {
  /* %typemap(csout) (char *), (char *&), (char[ANY]), (char[]), (const char *utf8_string) */
  IntPtr cPtr = GdalPINVOKE.MDArray_GetUnit(swigCPtr);
  string ret = GdalPINVOKE.LengthPrefixedUtf16UnmanagedToString(cPtr);
  
    if (GdalPINVOKE.SWIGPendingException.Pending) throw GdalPINVOKE.SWIGPendingException.Retrieve();
  return ret;
}

  public MDArray GetView(string viewExpr) {
    IntPtr tempviewExpr = GdalPINVOKE.StringToUtf8Unmanaged(viewExpr);
    try {
      IntPtr cPtr = GdalPINVOKE.MDArray_GetView(swigCPtr, tempviewExpr);
      MDArray ret = (cPtr == IntPtr.Zero) ? null : new MDArray(cPtr, true, ThisOwn_true());
      if (GdalPINVOKE.SWIGPendingException.Pending) throw GdalPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } finally {
    System.Runtime.InteropServices.Marshal.FreeHGlobal(tempviewExpr);
    }
  }

  public MDArray Transpose(int axisMap, int[] mapInts) {
    GCHandle swig_handleTo_mapInts = GCHandle.Alloc(mapInts, GCHandleType.Pinned);
    try {
    {
      IntPtr cPtr = GdalPINVOKE.MDArray_Transpose(swigCPtr, axisMap, swig_handleTo_mapInts.AddrOfPinnedObject());
      MDArray ret = (cPtr == IntPtr.Zero) ? null : new MDArray(cPtr, true, ThisOwn_true());
      if (GdalPINVOKE.SWIGPendingException.Pending) throw GdalPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    }
    } finally {
        swig_handleTo_mapInts.Free();
        GC.KeepAlive(this);
    }
  }

  public MDArray GetUnscaled() {
    IntPtr cPtr = GdalPINVOKE.MDArray_GetUnscaled(swigCPtr);
    MDArray ret = (cPtr == IntPtr.Zero) ? null : new MDArray(cPtr, true, ThisOwn_true());
    if (GdalPINVOKE.SWIGPendingException.Pending) throw GdalPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public MDArray GetMask(string[] options) {
    using (var tempoptions = new GdalPINVOKE.StringListMarshal(options)) { 
    {
      IntPtr cPtr = GdalPINVOKE.MDArray_GetMask(swigCPtr, tempoptions._ar);
      MDArray ret = (cPtr == IntPtr.Zero) ? null : new MDArray(cPtr, true, ThisOwn_true());
      if (GdalPINVOKE.SWIGPendingException.Pending) throw GdalPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    }
    }
  }

  public MDArray GetGridded(string pszGridOptions, MDArray xArray, MDArray yArray, string[] options) {
    IntPtr temppszGridOptions = GdalPINVOKE.StringToUtf8Unmanaged(pszGridOptions);
    using (var tempoptions = new GdalPINVOKE.StringListMarshal(options)) { 
    try {
      IntPtr cPtr = GdalPINVOKE.MDArray_GetGridded(swigCPtr, temppszGridOptions, MDArray.getCPtr(xArray), MDArray.getCPtr(yArray), tempoptions._ar);
      MDArray ret = (cPtr == IntPtr.Zero) ? null : new MDArray(cPtr, true, ThisOwn_true());
      if (GdalPINVOKE.SWIGPendingException.Pending) throw GdalPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } finally {
    System.Runtime.InteropServices.Marshal.FreeHGlobal(temppszGridOptions);
    }
    }
  }

  public Dataset AsClassicDataset(uint iXDim, uint iYDim, Group hRootGroup, string[] options) {
    using (var tempoptions = new GdalPINVOKE.StringListMarshal(options)) { 
    {
      IntPtr cPtr = GdalPINVOKE.MDArray_AsClassicDataset(swigCPtr, iXDim, iYDim, Group.getCPtr(hRootGroup), tempoptions._ar);
      Dataset ret = (cPtr == IntPtr.Zero) ? null : new Dataset(cPtr, true, ThisOwn_true());
      if (GdalPINVOKE.SWIGPendingException.Pending) throw GdalPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    }
    }
  }

  public bool Cache(string[] options) {
    using (var tempoptions = new GdalPINVOKE.StringListMarshal(options)) { 
    {
      bool ret = GdalPINVOKE.MDArray_Cache(swigCPtr, tempoptions._ar);
      if (GdalPINVOKE.SWIGPendingException.Pending) throw GdalPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    }
    }
  }

  public CPLErr Rename(string newName) {
    IntPtr tempnewName = GdalPINVOKE.StringToUtf8Unmanaged(newName);
    try {
      CPLErr ret = (CPLErr)GdalPINVOKE.MDArray_Rename(swigCPtr, tempnewName);
      if (GdalPINVOKE.SWIGPendingException.Pending) throw GdalPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } finally {
    System.Runtime.InteropServices.Marshal.FreeHGlobal(tempnewName);
    }
  }

  public int GetOverviewCount() {
    int ret = GdalPINVOKE.MDArray_GetOverviewCount(swigCPtr);
    if (GdalPINVOKE.SWIGPendingException.Pending) throw GdalPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public MDArray GetOverview(int idx) {
    IntPtr cPtr = GdalPINVOKE.MDArray_GetOverview(swigCPtr, idx);
    MDArray ret = (cPtr == IntPtr.Zero) ? null : new MDArray(cPtr, true, ThisOwn_true());
    if (GdalPINVOKE.SWIGPendingException.Pending) throw GdalPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public CPLErr BuildOverviews(string resampling, int overviewlist, SWIGTYPE_p_int pOverviews, Gdal.GDALProgressFuncDelegate callback, string callback_data, string[] options) {
    IntPtr tempresampling = GdalPINVOKE.StringToUtf8Unmanaged(resampling);
    IntPtr tempcallback_data = GdalPINVOKE.StringToUtf8Unmanaged(callback_data);
    using (var tempoptions = new GdalPINVOKE.StringListMarshal(options)) { 
    try {
      CPLErr ret = (CPLErr)GdalPINVOKE.MDArray_BuildOverviews(swigCPtr, tempresampling, overviewlist, SWIGTYPE_p_int.getCPtr(pOverviews), callback, tempcallback_data, tempoptions._ar);
      if (GdalPINVOKE.SWIGPendingException.Pending) throw GdalPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } finally {
    System.Runtime.InteropServices.Marshal.FreeHGlobal(tempresampling);
    System.Runtime.InteropServices.Marshal.FreeHGlobal(tempcallback_data);
    }
    }
  }

  public int GuessGeoTransform(uint nDimX, uint nDimY, bool bPixelIsPoint, double[] padfGeoTransform) {
    int res = GdalPINVOKE.MDArray_GuessGeoTransform(swigCPtr, nDimX, nDimY, bPixelIsPoint, padfGeoTransform);
    if (GdalPINVOKE.SWIGPendingException.Pending) throw GdalPINVOKE.SWIGPendingException.Retrieve();
    return res;
}

}

}
