//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace OSGeo.GDAL {

public enum RasterAlgebraUnaryOperation {
  GRAUO_LOGICAL_NOT = 0,
  GRAUO_ABS = 1,
  GRAUO_SQRT = 2,
  GRAUO_LOG = 3,
  GRAUO_LOG10 = 4
}

}
