//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace OSGeo.GDAL {

public enum RelationshipCardinality {
  GRC_ONE_TO_ONE = 0,
  GRC_ONE_TO_MANY = 1,
  GRC_MANY_TO_ONE = 2,
  GRC_MANY_TO_MANY = 3
}

}
