//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace OSGeo.GDAL {

public enum RelationshipType {
  GRT_COMPOSITE = 0,
  GRT_ASSOCIATION = 1,
  GRT_AGGREGATION = 2
}

}
