//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace OSGeo.GDAL {

using global::System;
using global::System.Runtime.InteropServices;

public class XMLNode : global::System.IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;
  protected object swigParentRef;

  protected static object ThisOwn_true() { return null; }
  protected object ThisOwn_false() { return this; }

  public XMLNode(IntPtr cPtr, bool cMemoryOwn, object parent) {
    swigCMemOwn = cMemoryOwn;
    swigParentRef = parent;
    swigCPtr = new HandleRef(this, cPtr);
  }

  public static HandleRef getCPtr(XMLNode obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }
  public static HandleRef getCPtrAndDisown(XMLNode obj, object parent) {
    if (obj != null)
    {
      obj.swigCMemOwn = false;
      obj.swigParentRef = parent;
      return obj.swigCPtr;
    }
    else
    {
      return new HandleRef(null, IntPtr.Zero);
    }
  }
  public static HandleRef getCPtrAndSetReference(XMLNode obj, object parent) {
    if (obj != null)
    {
      obj.swigParentRef = parent;
      return obj.swigCPtr;
    }
    else
    {
      return new HandleRef(null, IntPtr.Zero);
    }
  }

  ~XMLNode() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          GdalPINVOKE.delete_XMLNode(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public XMLNodeType Type {
    get {
      XMLNodeType ret = (XMLNodeType)GdalPINVOKE.XMLNode_Type_get(swigCPtr);
      if (GdalPINVOKE.SWIGPendingException.Pending) throw GdalPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public string Value {
  get {
    /* %typemap(csvarout) (char *), (char *&), (char[ANY]), (char[]), (const char *utf8_string) */
    IntPtr cPtr = GdalPINVOKE.XMLNode_Value_get(swigCPtr);
    string ret = GdalPINVOKE.LengthPrefixedUtf16UnmanagedToString(cPtr);
    
      if (GdalPINVOKE.SWIGPendingException.Pending) throw GdalPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  }

  public XMLNode Next {
    get {
      IntPtr cPtr = GdalPINVOKE.XMLNode_Next_get(swigCPtr);
      XMLNode ret = (cPtr == IntPtr.Zero) ? null : new XMLNode(cPtr, false, ThisOwn_false());
      if (GdalPINVOKE.SWIGPendingException.Pending) throw GdalPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public XMLNode Child {
    get {
      IntPtr cPtr = GdalPINVOKE.XMLNode_Child_get(swigCPtr);
      XMLNode ret = (cPtr == IntPtr.Zero) ? null : new XMLNode(cPtr, false, ThisOwn_false());
      if (GdalPINVOKE.SWIGPendingException.Pending) throw GdalPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  static private global::System.IntPtr SwigConstructXMLNode(string pszString) {
    IntPtr temppszString = GdalPINVOKE.StringToUtf8Unmanaged(pszString);
    try {
      return GdalPINVOKE.new_XMLNode__SWIG_0(temppszString);
    } finally {
    System.Runtime.InteropServices.Marshal.FreeHGlobal(temppszString);
    }
  }

  public XMLNode(string pszString) : this(XMLNode.SwigConstructXMLNode(pszString), true, null) {
    if (GdalPINVOKE.SWIGPendingException.Pending) throw GdalPINVOKE.SWIGPendingException.Retrieve();
  }

  static private global::System.IntPtr SwigConstructXMLNode(XMLNodeType eType, string pszText) {
    IntPtr temppszText = GdalPINVOKE.StringToUtf8Unmanaged(pszText);
    try {
      return GdalPINVOKE.new_XMLNode__SWIG_1((int)eType, temppszText);
    } finally {
    System.Runtime.InteropServices.Marshal.FreeHGlobal(temppszText);
    }
  }

  public XMLNode(XMLNodeType eType, string pszText) : this(XMLNode.SwigConstructXMLNode(eType, pszText), true, null) {
    if (GdalPINVOKE.SWIGPendingException.Pending) throw GdalPINVOKE.SWIGPendingException.Retrieve();
  }

  public string SerializeXMLTree() {
  /* %typemap(csout) (char *), (char *&), (char[ANY]), (char[]), (const char *utf8_string) */
  IntPtr cPtr = GdalPINVOKE.XMLNode_SerializeXMLTree(swigCPtr);
  string ret = GdalPINVOKE.LengthPrefixedUtf16UnmanagedToString(cPtr);
  
    if (GdalPINVOKE.SWIGPendingException.Pending) throw GdalPINVOKE.SWIGPendingException.Retrieve();
  return ret;
}

  public string toString() {
  /* %typemap(csout) (char *), (char *&), (char[ANY]), (char[]), (const char *utf8_string) */
  IntPtr cPtr = GdalPINVOKE.XMLNode_toString(swigCPtr);
  string ret = GdalPINVOKE.LengthPrefixedUtf16UnmanagedToString(cPtr);
  
    if (GdalPINVOKE.SWIGPendingException.Pending) throw GdalPINVOKE.SWIGPendingException.Retrieve();
  return ret;
}

  public XMLNode SearchXMLNode(string pszElement) {
    IntPtr temppszElement = GdalPINVOKE.StringToUtf8Unmanaged(pszElement);
    try {
      IntPtr cPtr = GdalPINVOKE.XMLNode_SearchXMLNode(swigCPtr, temppszElement);
      XMLNode ret = (cPtr == IntPtr.Zero) ? null : new XMLNode(cPtr, false, ThisOwn_false());
      if (GdalPINVOKE.SWIGPendingException.Pending) throw GdalPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } finally {
    System.Runtime.InteropServices.Marshal.FreeHGlobal(temppszElement);
    }
  }

  public XMLNode GetXMLNode(string pszPath) {
    IntPtr temppszPath = GdalPINVOKE.StringToUtf8Unmanaged(pszPath);
    try {
      IntPtr cPtr = GdalPINVOKE.XMLNode_GetXMLNode(swigCPtr, temppszPath);
      XMLNode ret = (cPtr == IntPtr.Zero) ? null : new XMLNode(cPtr, false, ThisOwn_false());
      if (GdalPINVOKE.SWIGPendingException.Pending) throw GdalPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } finally {
    System.Runtime.InteropServices.Marshal.FreeHGlobal(temppszPath);
    }
  }

  public string GetXMLValue(string pszPath, string pszDefault) {
    IntPtr temppszPath = GdalPINVOKE.StringToUtf8Unmanaged(pszPath);
    IntPtr temppszDefault = GdalPINVOKE.StringToUtf8Unmanaged(pszDefault);
    try {
    /* %typemap(csout) (char *), (char *&), (char[ANY]), (char[]), (const char *utf8_string) */
    IntPtr cPtr = GdalPINVOKE.XMLNode_GetXMLValue(swigCPtr, temppszPath, temppszDefault);
    string ret = GdalPINVOKE.LengthPrefixedUtf16UnmanagedToString(cPtr);
    
      if (GdalPINVOKE.SWIGPendingException.Pending) throw GdalPINVOKE.SWIGPendingException.Retrieve();
    return ret;
} finally {
    System.Runtime.InteropServices.Marshal.FreeHGlobal(temppszPath);
    System.Runtime.InteropServices.Marshal.FreeHGlobal(temppszDefault);
    }
  }

  public void AddXMLChild(XMLNode psChild) {
    GdalPINVOKE.XMLNode_AddXMLChild(swigCPtr, XMLNode.getCPtr(psChild));
    if (GdalPINVOKE.SWIGPendingException.Pending) throw GdalPINVOKE.SWIGPendingException.Retrieve();
  }

  public int RemoveXMLChild(XMLNode psChild) {
    int ret = GdalPINVOKE.XMLNode_RemoveXMLChild(swigCPtr, XMLNode.getCPtr(psChild));
    if (GdalPINVOKE.SWIGPendingException.Pending) throw GdalPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void AddXMLSibling(XMLNode psNewSibling) {
    GdalPINVOKE.XMLNode_AddXMLSibling(swigCPtr, XMLNode.getCPtr(psNewSibling));
    if (GdalPINVOKE.SWIGPendingException.Pending) throw GdalPINVOKE.SWIGPendingException.Retrieve();
  }

  public XMLNode CreateXMLElementAndValue(string pszName, string pszValue) {
    IntPtr temppszName = GdalPINVOKE.StringToUtf8Unmanaged(pszName);
    IntPtr temppszValue = GdalPINVOKE.StringToUtf8Unmanaged(pszValue);
    try {
      IntPtr cPtr = GdalPINVOKE.XMLNode_CreateXMLElementAndValue(swigCPtr, temppszName, temppszValue);
      XMLNode ret = (cPtr == IntPtr.Zero) ? null : new XMLNode(cPtr, false, ThisOwn_false());
      if (GdalPINVOKE.SWIGPendingException.Pending) throw GdalPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } finally {
    System.Runtime.InteropServices.Marshal.FreeHGlobal(temppszName);
    System.Runtime.InteropServices.Marshal.FreeHGlobal(temppszValue);
    }
  }

  public XMLNode CloneXMLTree(XMLNode psTree) {
    IntPtr cPtr = GdalPINVOKE.XMLNode_CloneXMLTree(swigCPtr, XMLNode.getCPtr(psTree));
    XMLNode ret = (cPtr == IntPtr.Zero) ? null : new XMLNode(cPtr, true, ThisOwn_true());
    if (GdalPINVOKE.SWIGPendingException.Pending) throw GdalPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public XMLNode Clone() {
    IntPtr cPtr = GdalPINVOKE.XMLNode_Clone(swigCPtr);
    XMLNode ret = (cPtr == IntPtr.Zero) ? null : new XMLNode(cPtr, true, ThisOwn_true());
    if (GdalPINVOKE.SWIGPendingException.Pending) throw GdalPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int SetXMLValue(string pszPath, string pszValue) {
    IntPtr temppszPath = GdalPINVOKE.StringToUtf8Unmanaged(pszPath);
    IntPtr temppszValue = GdalPINVOKE.StringToUtf8Unmanaged(pszValue);
    try {
      int ret = GdalPINVOKE.XMLNode_SetXMLValue(swigCPtr, temppszPath, temppszValue);
      if (GdalPINVOKE.SWIGPendingException.Pending) throw GdalPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } finally {
    System.Runtime.InteropServices.Marshal.FreeHGlobal(temppszPath);
    System.Runtime.InteropServices.Marshal.FreeHGlobal(temppszValue);
    }
  }

  public void StripXMLNamespace(string pszNamespace, int bRecurse) {
    IntPtr temppszNamespace = GdalPINVOKE.StringToUtf8Unmanaged(pszNamespace);
    try {
      GdalPINVOKE.XMLNode_StripXMLNamespace(swigCPtr, temppszNamespace, bRecurse);
      if (GdalPINVOKE.SWIGPendingException.Pending) throw GdalPINVOKE.SWIGPendingException.Retrieve();
    } finally {
    System.Runtime.InteropServices.Marshal.FreeHGlobal(temppszNamespace);
    }
  }

}

}
