//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace OSGeo.OGR {

using global::System;
using global::System.Runtime.InteropServices;

public class DataSource : global::System.IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;
  protected object swigParentRef;

  protected static object ThisOwn_true() { return null; }
  protected object ThisOwn_false() { return this; }

  public DataSource(IntPtr cPtr, bool cMemoryOwn, object parent) {
    swigCMemOwn = cMemoryOwn;
    swigParentRef = parent;
    swigCPtr = new HandleRef(this, cPtr);
  }

  public static HandleRef getCPtr(DataSource obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }
  public static HandleRef getCPtrAndDisown(DataSource obj, object parent) {
    if (obj != null)
    {
      obj.swigCMemOwn = false;
      obj.swigParentRef = parent;
      return obj.swigCPtr;
    }
    else
    {
      return new HandleRef(null, IntPtr.Zero);
    }
  }
  public static HandleRef getCPtrAndSetReference(DataSource obj, object parent) {
    if (obj != null)
    {
      obj.swigParentRef = parent;
      return obj.swigCPtr;
    }
    else
    {
      return new HandleRef(null, IntPtr.Zero);
    }
  }

  ~DataSource() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          OgrPINVOKE.delete_DataSource(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public string name {
  get {
    /* %typemap(csvarout) (char *), (char *&), (char[ANY]), (char[]), (const char *utf8_string) */
    IntPtr cPtr = OgrPINVOKE.DataSource_name_get(swigCPtr);
    string ret = OgrPINVOKE.LengthPrefixedUtf16UnmanagedToString(cPtr);
    
      if (OgrPINVOKE.SWIGPendingException.Pending) throw OgrPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  }

  public int Close() {
    int ret = OgrPINVOKE.DataSource_Close(swigCPtr);
    if (OgrPINVOKE.SWIGPendingException.Pending) throw OgrPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int GetRefCount() {
    int ret = OgrPINVOKE.DataSource_GetRefCount(swigCPtr);
    if (OgrPINVOKE.SWIGPendingException.Pending) throw OgrPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int GetSummaryRefCount() {
    int ret = OgrPINVOKE.DataSource_GetSummaryRefCount(swigCPtr);
    if (OgrPINVOKE.SWIGPendingException.Pending) throw OgrPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int GetLayerCount() {
    int ret = OgrPINVOKE.DataSource_GetLayerCount(swigCPtr);
    if (OgrPINVOKE.SWIGPendingException.Pending) throw OgrPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Driver GetDriver() {
    IntPtr cPtr = OgrPINVOKE.DataSource_GetDriver(swigCPtr);
    Driver ret = (cPtr == IntPtr.Zero) ? null : new Driver(cPtr, false, ThisOwn_false());
    if (OgrPINVOKE.SWIGPendingException.Pending) throw OgrPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string GetName() {
  /* %typemap(csout) (char *), (char *&), (char[ANY]), (char[]), (const char *utf8_string) */
  IntPtr cPtr = OgrPINVOKE.DataSource_GetName(swigCPtr);
  string ret = OgrPINVOKE.LengthPrefixedUtf16UnmanagedToString(cPtr);
  
    if (OgrPINVOKE.SWIGPendingException.Pending) throw OgrPINVOKE.SWIGPendingException.Retrieve();
  return ret;
}

  public int DeleteLayer(int index) {
    int ret = OgrPINVOKE.DataSource_DeleteLayer(swigCPtr, index);
    if (OgrPINVOKE.SWIGPendingException.Pending) throw OgrPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int SyncToDisk() {
    int ret = OgrPINVOKE.DataSource_SyncToDisk(swigCPtr);
    if (OgrPINVOKE.SWIGPendingException.Pending) throw OgrPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void FlushCache() {
    OgrPINVOKE.DataSource_FlushCache(swigCPtr);
    if (OgrPINVOKE.SWIGPendingException.Pending) throw OgrPINVOKE.SWIGPendingException.Retrieve();
  }

  public Layer CreateLayer(string name, OSGeo.OSR.SpatialReference srs, wkbGeometryType geom_type, string[] options) {
    IntPtr tempname = OgrPINVOKE.StringToUtf8Unmanaged(name);
    using (var tempoptions = new OgrPINVOKE.StringListMarshal(options)) { 
    try {
      IntPtr cPtr = OgrPINVOKE.DataSource_CreateLayer(swigCPtr, tempname, OSGeo.OSR.SpatialReference.getCPtr(srs), (int)geom_type, tempoptions._ar);
      Layer ret = (cPtr == IntPtr.Zero) ? null : new Layer(cPtr, false, ThisOwn_false());
      if (OgrPINVOKE.SWIGPendingException.Pending) throw OgrPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } finally {
    System.Runtime.InteropServices.Marshal.FreeHGlobal(tempname);
    }
    }
  }

  public Layer CopyLayer(Layer src_layer, string new_name, string[] options) {
    IntPtr tempnew_name = OgrPINVOKE.StringToUtf8Unmanaged(new_name);
    using (var tempoptions = new OgrPINVOKE.StringListMarshal(options)) { 
    try {
      IntPtr cPtr = OgrPINVOKE.DataSource_CopyLayer(swigCPtr, Layer.getCPtr(src_layer), tempnew_name, tempoptions._ar);
      Layer ret = (cPtr == IntPtr.Zero) ? null : new Layer(cPtr, false, ThisOwn_false());
      if (OgrPINVOKE.SWIGPendingException.Pending) throw OgrPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } finally {
    System.Runtime.InteropServices.Marshal.FreeHGlobal(tempnew_name);
    }
    }
  }

  public Layer GetLayerByIndex(int index) {
    IntPtr cPtr = OgrPINVOKE.DataSource_GetLayerByIndex(swigCPtr, index);
    Layer ret = (cPtr == IntPtr.Zero) ? null : new Layer(cPtr, false, ThisOwn_false());
    if (OgrPINVOKE.SWIGPendingException.Pending) throw OgrPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Layer GetLayerByName(string layer_name) {
    IntPtr templayer_name = OgrPINVOKE.StringToUtf8Unmanaged(layer_name);
    try {
      IntPtr cPtr = OgrPINVOKE.DataSource_GetLayerByName(swigCPtr, templayer_name);
      Layer ret = (cPtr == IntPtr.Zero) ? null : new Layer(cPtr, false, ThisOwn_false());
      if (OgrPINVOKE.SWIGPendingException.Pending) throw OgrPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } finally {
    System.Runtime.InteropServices.Marshal.FreeHGlobal(templayer_name);
    }
  }

  public bool TestCapability(string cap) {
    IntPtr tempcap = OgrPINVOKE.StringToUtf8Unmanaged(cap);
    try {
      bool ret = OgrPINVOKE.DataSource_TestCapability(swigCPtr, tempcap);
      if (OgrPINVOKE.SWIGPendingException.Pending) throw OgrPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } finally {
    System.Runtime.InteropServices.Marshal.FreeHGlobal(tempcap);
    }
  }

  public Layer ExecuteSQL(string statement, Geometry spatialFilter, string dialect) {
    IntPtr tempstatement = OgrPINVOKE.StringToUtf8Unmanaged(statement);
    IntPtr tempdialect = OgrPINVOKE.StringToUtf8Unmanaged(dialect);
    try {
      IntPtr cPtr = OgrPINVOKE.DataSource_ExecuteSQL(swigCPtr, tempstatement, Geometry.getCPtr(spatialFilter), tempdialect);
      Layer ret = (cPtr == IntPtr.Zero) ? null : new Layer(cPtr, false, ThisOwn_false());
      if (OgrPINVOKE.SWIGPendingException.Pending) throw OgrPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } finally {
    System.Runtime.InteropServices.Marshal.FreeHGlobal(tempstatement);
    System.Runtime.InteropServices.Marshal.FreeHGlobal(tempdialect);
    }
  }

  public int AbortSQL() {
    int ret = OgrPINVOKE.DataSource_AbortSQL(swigCPtr);
    if (OgrPINVOKE.SWIGPendingException.Pending) throw OgrPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void ReleaseResultSet(Layer layer) {
    OgrPINVOKE.DataSource_ReleaseResultSet(swigCPtr, Layer.getCPtrAndDisown(layer, ThisOwn_false()));
    if (OgrPINVOKE.SWIGPendingException.Pending) throw OgrPINVOKE.SWIGPendingException.Retrieve();
  }

  public StyleTable GetStyleTable() {
    IntPtr cPtr = OgrPINVOKE.DataSource_GetStyleTable(swigCPtr);
    StyleTable ret = (cPtr == IntPtr.Zero) ? null : new StyleTable(cPtr, false, ThisOwn_false());
    if (OgrPINVOKE.SWIGPendingException.Pending) throw OgrPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetStyleTable(StyleTable table) {
    OgrPINVOKE.DataSource_SetStyleTable(swigCPtr, StyleTable.getCPtr(table));
    if (OgrPINVOKE.SWIGPendingException.Pending) throw OgrPINVOKE.SWIGPendingException.Retrieve();
  }

  public int StartTransaction(int force) {
    int ret = OgrPINVOKE.DataSource_StartTransaction(swigCPtr, force);
    if (OgrPINVOKE.SWIGPendingException.Pending) throw OgrPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int CommitTransaction() {
    int ret = OgrPINVOKE.DataSource_CommitTransaction(swigCPtr);
    if (OgrPINVOKE.SWIGPendingException.Pending) throw OgrPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int RollbackTransaction() {
    int ret = OgrPINVOKE.DataSource_RollbackTransaction(swigCPtr);
    if (OgrPINVOKE.SWIGPendingException.Pending) throw OgrPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
