//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace OSGeo.OGR {

using global::System;
using global::System.Runtime.InteropServices;

public class Driver : global::System.IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;
  protected object swigParentRef;

  protected static object ThisOwn_true() { return null; }
  protected object ThisOwn_false() { return this; }

  public Driver(IntPtr cPtr, bool cMemoryOwn, object parent) {
    swigCMemOwn = cMemoryOwn;
    swigParentRef = parent;
    swigCPtr = new HandleRef(this, cPtr);
  }

  public static HandleRef getCPtr(Driver obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }
  public static HandleRef getCPtrAndDisown(Driver obj, object parent) {
    if (obj != null)
    {
      obj.swigCMemOwn = false;
      obj.swigParentRef = parent;
      return obj.swigCPtr;
    }
    else
    {
      return new HandleRef(null, IntPtr.Zero);
    }
  }
  public static HandleRef getCPtrAndSetReference(Driver obj, object parent) {
    if (obj != null)
    {
      obj.swigParentRef = parent;
      return obj.swigCPtr;
    }
    else
    {
      return new HandleRef(null, IntPtr.Zero);
    }
  }

  ~Driver() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          throw new global::System.MethodAccessException("C++ destructor does not have public access");
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public string name {
  get {
    /* %typemap(csvarout) (char *), (char *&), (char[ANY]), (char[]), (const char *utf8_string) */
    IntPtr cPtr = OgrPINVOKE.Driver_name_get(swigCPtr);
    string ret = OgrPINVOKE.LengthPrefixedUtf16UnmanagedToString(cPtr);
    
      if (OgrPINVOKE.SWIGPendingException.Pending) throw OgrPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  }

  public DataSource CreateDataSource(string utf8_string, string[] options) {
    IntPtr temputf8_string = OgrPINVOKE.StringToUtf8Unmanaged(utf8_string);
    using (var tempoptions = new OgrPINVOKE.StringListMarshal(options)) { 
    try {
      IntPtr cPtr = OgrPINVOKE.Driver_CreateDataSource(swigCPtr, temputf8_string, tempoptions._ar);
      DataSource ret = (cPtr == IntPtr.Zero) ? null : new DataSource(cPtr, true, ThisOwn_true());
      if (OgrPINVOKE.SWIGPendingException.Pending) throw OgrPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } finally {
    System.Runtime.InteropServices.Marshal.FreeHGlobal(temputf8_string);
    }
    }
  }

  public DataSource CopyDataSource(DataSource copy_ds, string utf8_string, string[] options) {
    IntPtr temputf8_string = OgrPINVOKE.StringToUtf8Unmanaged(utf8_string);
    using (var tempoptions = new OgrPINVOKE.StringListMarshal(options)) { 
    try {
      IntPtr cPtr = OgrPINVOKE.Driver_CopyDataSource(swigCPtr, DataSource.getCPtr(copy_ds), temputf8_string, tempoptions._ar);
      DataSource ret = (cPtr == IntPtr.Zero) ? null : new DataSource(cPtr, true, ThisOwn_true());
      if (OgrPINVOKE.SWIGPendingException.Pending) throw OgrPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } finally {
    System.Runtime.InteropServices.Marshal.FreeHGlobal(temputf8_string);
    }
    }
  }

  public DataSource Open(string utf8_string, int update) {
    IntPtr temputf8_string = OgrPINVOKE.StringToUtf8Unmanaged(utf8_string);
    try {
      IntPtr cPtr = OgrPINVOKE.Driver_Open(swigCPtr, temputf8_string, update);
      DataSource ret = (cPtr == IntPtr.Zero) ? null : new DataSource(cPtr, true, ThisOwn_true());
      if (OgrPINVOKE.SWIGPendingException.Pending) throw OgrPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } finally {
    System.Runtime.InteropServices.Marshal.FreeHGlobal(temputf8_string);
    }
  }

  public int DeleteDataSource(string utf8_string) {
    IntPtr temputf8_string = OgrPINVOKE.StringToUtf8Unmanaged(utf8_string);
    try {
      int ret = OgrPINVOKE.Driver_DeleteDataSource(swigCPtr, temputf8_string);
      if (OgrPINVOKE.SWIGPendingException.Pending) throw OgrPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } finally {
    System.Runtime.InteropServices.Marshal.FreeHGlobal(temputf8_string);
    }
  }

  public bool TestCapability(string cap) {
    IntPtr tempcap = OgrPINVOKE.StringToUtf8Unmanaged(cap);
    try {
      bool ret = OgrPINVOKE.Driver_TestCapability(swigCPtr, tempcap);
      if (OgrPINVOKE.SWIGPendingException.Pending) throw OgrPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } finally {
    System.Runtime.InteropServices.Marshal.FreeHGlobal(tempcap);
    }
  }

  public string GetName() {
  /* %typemap(csout) (char *), (char *&), (char[ANY]), (char[]), (const char *utf8_string) */
  IntPtr cPtr = OgrPINVOKE.Driver_GetName(swigCPtr);
  string ret = OgrPINVOKE.LengthPrefixedUtf16UnmanagedToString(cPtr);
  
    if (OgrPINVOKE.SWIGPendingException.Pending) throw OgrPINVOKE.SWIGPendingException.Retrieve();
  return ret;
}

  public void Register() {
    OgrPINVOKE.Driver_Register(swigCPtr);
    if (OgrPINVOKE.SWIGPendingException.Pending) throw OgrPINVOKE.SWIGPendingException.Retrieve();
  }

  public void Deregister() {
    OgrPINVOKE.Driver_Deregister(swigCPtr);
    if (OgrPINVOKE.SWIGPendingException.Pending) throw OgrPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
