//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace OSGeo.OGR {

public enum FieldDomainType {
  OFDT_CODED = 0,
  OFDT_RANGE = 1,
  OFDT_GLOB = 2
}

}
