//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace OSGeo.OGR {

public enum FieldType {
  OFTInteger = 0,
  OFTIntegerList = 1,
  OFTReal = 2,
  OFTRealList = 3,
  OFTString = 4,
  OFTStringList = 5,
  OFTWideString = 6,
  OFTWideStringList = 7,
  OFTBinary = 8,
  OFTDate = 9,
  OFTTime = 10,
  OFTDateTime = 11,
  OFTInteger64 = 12,
  OFTInteger64List = 13
}

}
