//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace OSGeo.OGR {

using global::System;
using global::System.Runtime.InteropServices;

public class GeomCoordinatePrecision : global::System.IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;
  protected object swigParentRef;

  protected static object ThisOwn_true() { return null; }
  protected object ThisOwn_false() { return this; }

  public GeomCoordinatePrecision(IntPtr cPtr, bool cMemoryOwn, object parent) {
    swigCMemOwn = cMemoryOwn;
    swigParentRef = parent;
    swigCPtr = new HandleRef(this, cPtr);
  }

  public static HandleRef getCPtr(GeomCoordinatePrecision obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }
  public static HandleRef getCPtrAndDisown(GeomCoordinatePrecision obj, object parent) {
    if (obj != null)
    {
      obj.swigCMemOwn = false;
      obj.swigParentRef = parent;
      return obj.swigCPtr;
    }
    else
    {
      return new HandleRef(null, IntPtr.Zero);
    }
  }
  public static HandleRef getCPtrAndSetReference(GeomCoordinatePrecision obj, object parent) {
    if (obj != null)
    {
      obj.swigParentRef = parent;
      return obj.swigCPtr;
    }
    else
    {
      return new HandleRef(null, IntPtr.Zero);
    }
  }

  ~GeomCoordinatePrecision() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          OgrPINVOKE.delete_GeomCoordinatePrecision(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public void Set(double xyResolution, double zResolution, double mResolution) {
    OgrPINVOKE.GeomCoordinatePrecision_Set(swigCPtr, xyResolution, zResolution, mResolution);
    if (OgrPINVOKE.SWIGPendingException.Pending) throw OgrPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetFromMeter(OSGeo.OSR.SpatialReference srs, double xyMeterResolution, double zMeterResolution, double mResolution) {
    OgrPINVOKE.GeomCoordinatePrecision_SetFromMeter(swigCPtr, OSGeo.OSR.SpatialReference.getCPtr(srs), xyMeterResolution, zMeterResolution, mResolution);
    if (OgrPINVOKE.SWIGPendingException.Pending) throw OgrPINVOKE.SWIGPendingException.Retrieve();
  }

  public double GetXYResolution() {
    double ret = OgrPINVOKE.GeomCoordinatePrecision_GetXYResolution(swigCPtr);
    if (OgrPINVOKE.SWIGPendingException.Pending) throw OgrPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double GetZResolution() {
    double ret = OgrPINVOKE.GeomCoordinatePrecision_GetZResolution(swigCPtr);
    if (OgrPINVOKE.SWIGPendingException.Pending) throw OgrPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double GetMResolution() {
    double ret = OgrPINVOKE.GeomCoordinatePrecision_GetMResolution(swigCPtr);
    if (OgrPINVOKE.SWIGPendingException.Pending) throw OgrPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string[] GetFormats() {
  /* %typemap(csout) char** CSL, char **dictAndCSLDestroy */
  /*@SWIG:C:/Users/runes/miniconda3/conda-bld/gdal-csharp_1779183890733/work/swig/include/csharp\csharp_strings.i,304,CS_MARSHAL_STRING_LIST@*/
  IntPtr cPtr = OgrPINVOKE.GeomCoordinatePrecision_GetFormats(swigCPtr);
  IntPtr objPtr;
  int count = 0;
  if (cPtr != IntPtr.Zero) {
    while (System.Runtime.InteropServices.Marshal.ReadIntPtr(cPtr, count*IntPtr.Size) != IntPtr.Zero)
      ++count;
  }
  string[] ret = new string[count];
  if (count > 0) {
    for(int cx = 0; cx < count; cx++) {
      objPtr = System.Runtime.InteropServices.Marshal.ReadIntPtr(cPtr, cx * System.Runtime.InteropServices.Marshal.SizeOf(typeof(IntPtr)));
      ret[cx]= (objPtr == IntPtr.Zero) ? null : Ogr.Utf8BytesToString(objPtr);
    }
  }
/*@SWIG@*/
  if (cPtr != IntPtr.Zero)
    OgrPINVOKE.StringListDestroy(cPtr);
  
    if (OgrPINVOKE.SWIGPendingException.Pending) throw OgrPINVOKE.SWIGPendingException.Retrieve();
  return ret;
}

  public string[] GetFormatSpecificOptions(string formatName) {
    IntPtr tempformatName = OgrPINVOKE.StringToUtf8Unmanaged(formatName);
    try {
    /* %typemap(csout) char**options, char **dict */
    /*@SWIG:C:/Users/runes/miniconda3/conda-bld/gdal-csharp_1779183890733/work/swig/include/csharp\csharp_strings.i,304,CS_MARSHAL_STRING_LIST@*/
    IntPtr cPtr = OgrPINVOKE.GeomCoordinatePrecision_GetFormatSpecificOptions(swigCPtr, tempformatName);
    IntPtr objPtr;
    int count = 0;
    if (cPtr != IntPtr.Zero) {
      while (System.Runtime.InteropServices.Marshal.ReadIntPtr(cPtr, count*IntPtr.Size) != IntPtr.Zero)
        ++count;
    }
    string[] ret = new string[count];
    if (count > 0) {
      for(int cx = 0; cx < count; cx++) {
        objPtr = System.Runtime.InteropServices.Marshal.ReadIntPtr(cPtr, cx * System.Runtime.InteropServices.Marshal.SizeOf(typeof(IntPtr)));
        ret[cx]= (objPtr == IntPtr.Zero) ? null : Ogr.Utf8BytesToString(objPtr);
      }
    }
/*@SWIG@*/
    
      if (OgrPINVOKE.SWIGPendingException.Pending) throw OgrPINVOKE.SWIGPendingException.Retrieve();
    return ret;
} finally {
    System.Runtime.InteropServices.Marshal.FreeHGlobal(tempformatName);
    }
  }

  public void SetFormatSpecificOptions(string formatName, string[] formatSpecificOptions) {
    IntPtr tempformatName = OgrPINVOKE.StringToUtf8Unmanaged(formatName);
    using (var tempformatSpecificOptions = new OgrPINVOKE.StringListMarshal(formatSpecificOptions)) { 
    try {
      OgrPINVOKE.GeomCoordinatePrecision_SetFormatSpecificOptions(swigCPtr, tempformatName, tempformatSpecificOptions._ar);
      if (OgrPINVOKE.SWIGPendingException.Pending) throw OgrPINVOKE.SWIGPendingException.Retrieve();
    } finally {
    System.Runtime.InteropServices.Marshal.FreeHGlobal(tempformatName);
    }
    }
  }

}

}
