//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace OSGeo.OGR {

using global::System;
using global::System.Runtime.InteropServices;

public class Layer : global::System.IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;
  protected object swigParentRef;

  protected static object ThisOwn_true() { return null; }
  protected object ThisOwn_false() { return this; }

  public Layer(IntPtr cPtr, bool cMemoryOwn, object parent) {
    swigCMemOwn = cMemoryOwn;
    swigParentRef = parent;
    swigCPtr = new HandleRef(this, cPtr);
  }

  public static HandleRef getCPtr(Layer obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }
  public static HandleRef getCPtrAndDisown(Layer obj, object parent) {
    if (obj != null)
    {
      obj.swigCMemOwn = false;
      obj.swigParentRef = parent;
      return obj.swigCPtr;
    }
    else
    {
      return new HandleRef(null, IntPtr.Zero);
    }
  }
  public static HandleRef getCPtrAndSetReference(Layer obj, object parent) {
    if (obj != null)
    {
      obj.swigParentRef = parent;
      return obj.swigCPtr;
    }
    else
    {
      return new HandleRef(null, IntPtr.Zero);
    }
  }

  ~Layer() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          throw new global::System.MethodAccessException("C++ destructor does not have public access");
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public int Rename(string new_name) {
    IntPtr tempnew_name = OgrPINVOKE.StringToUtf8Unmanaged(new_name);
    try {
      int ret = OgrPINVOKE.Layer_Rename(swigCPtr, tempnew_name);
      if (OgrPINVOKE.SWIGPendingException.Pending) throw OgrPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } finally {
    System.Runtime.InteropServices.Marshal.FreeHGlobal(tempnew_name);
    }
  }

  public int GetRefCount() {
    int ret = OgrPINVOKE.Layer_GetRefCount(swigCPtr);
    if (OgrPINVOKE.SWIGPendingException.Pending) throw OgrPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetSpatialFilter(Geometry filter) {
    OgrPINVOKE.Layer_SetSpatialFilter__SWIG_0(swigCPtr, Geometry.getCPtr(filter));
    if (OgrPINVOKE.SWIGPendingException.Pending) throw OgrPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetSpatialFilterRect(double minx, double miny, double maxx, double maxy) {
    OgrPINVOKE.Layer_SetSpatialFilterRect__SWIG_0(swigCPtr, minx, miny, maxx, maxy);
    if (OgrPINVOKE.SWIGPendingException.Pending) throw OgrPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetSpatialFilter(int iGeomField, Geometry filter) {
    OgrPINVOKE.Layer_SetSpatialFilter__SWIG_1(swigCPtr, iGeomField, Geometry.getCPtr(filter));
    if (OgrPINVOKE.SWIGPendingException.Pending) throw OgrPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetSpatialFilterRect(int iGeomField, double minx, double miny, double maxx, double maxy) {
    OgrPINVOKE.Layer_SetSpatialFilterRect__SWIG_1(swigCPtr, iGeomField, minx, miny, maxx, maxy);
    if (OgrPINVOKE.SWIGPendingException.Pending) throw OgrPINVOKE.SWIGPendingException.Retrieve();
  }

  public Geometry GetSpatialFilter() {
    IntPtr cPtr = OgrPINVOKE.Layer_GetSpatialFilter(swigCPtr);
    Geometry ret = (cPtr == IntPtr.Zero) ? null : new Geometry(cPtr, false, ThisOwn_false());
    if (OgrPINVOKE.SWIGPendingException.Pending) throw OgrPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int SetAttributeFilter(string filter_string) {
    IntPtr tempfilter_string = OgrPINVOKE.StringToUtf8Unmanaged(filter_string);
    try {
      int ret = OgrPINVOKE.Layer_SetAttributeFilter(swigCPtr, tempfilter_string);
      if (OgrPINVOKE.SWIGPendingException.Pending) throw OgrPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } finally {
    System.Runtime.InteropServices.Marshal.FreeHGlobal(tempfilter_string);
    }
  }

  public string GetAttributeFilter() {
  /* %typemap(csout) (char *), (char *&), (char[ANY]), (char[]), (const char *utf8_string) */
  IntPtr cPtr = OgrPINVOKE.Layer_GetAttributeFilter(swigCPtr);
  string ret = OgrPINVOKE.LengthPrefixedUtf16UnmanagedToString(cPtr);
  
    if (OgrPINVOKE.SWIGPendingException.Pending) throw OgrPINVOKE.SWIGPendingException.Retrieve();
  return ret;
}

  public void ResetReading() {
    OgrPINVOKE.Layer_ResetReading(swigCPtr);
    if (OgrPINVOKE.SWIGPendingException.Pending) throw OgrPINVOKE.SWIGPendingException.Retrieve();
  }

  public string GetName() {
  /* %typemap(csout) (char *), (char *&), (char[ANY]), (char[]), (const char *utf8_string) */
  IntPtr cPtr = OgrPINVOKE.Layer_GetName(swigCPtr);
  string ret = OgrPINVOKE.LengthPrefixedUtf16UnmanagedToString(cPtr);
  
    if (OgrPINVOKE.SWIGPendingException.Pending) throw OgrPINVOKE.SWIGPendingException.Retrieve();
  return ret;
}

  public wkbGeometryType GetGeomType() {
    wkbGeometryType ret = (wkbGeometryType)OgrPINVOKE.Layer_GetGeomType(swigCPtr);
    if (OgrPINVOKE.SWIGPendingException.Pending) throw OgrPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string GetGeometryColumn() {
  /* %typemap(csout) (char *), (char *&), (char[ANY]), (char[]), (const char *utf8_string) */
  IntPtr cPtr = OgrPINVOKE.Layer_GetGeometryColumn(swigCPtr);
  string ret = OgrPINVOKE.LengthPrefixedUtf16UnmanagedToString(cPtr);
  
    if (OgrPINVOKE.SWIGPendingException.Pending) throw OgrPINVOKE.SWIGPendingException.Retrieve();
  return ret;
}

  public string GetFIDColumn() {
  /* %typemap(csout) (char *), (char *&), (char[ANY]), (char[]), (const char *utf8_string) */
  IntPtr cPtr = OgrPINVOKE.Layer_GetFIDColumn(swigCPtr);
  string ret = OgrPINVOKE.LengthPrefixedUtf16UnmanagedToString(cPtr);
  
    if (OgrPINVOKE.SWIGPendingException.Pending) throw OgrPINVOKE.SWIGPendingException.Retrieve();
  return ret;
}

  public Feature GetFeature(long fid) {
    IntPtr cPtr = OgrPINVOKE.Layer_GetFeature(swigCPtr, fid);
    Feature ret = (cPtr == IntPtr.Zero) ? null : new Feature(cPtr, true, ThisOwn_true());
    if (OgrPINVOKE.SWIGPendingException.Pending) throw OgrPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Feature GetNextFeature() {
    IntPtr cPtr = OgrPINVOKE.Layer_GetNextFeature(swigCPtr);
    Feature ret = (cPtr == IntPtr.Zero) ? null : new Feature(cPtr, true, ThisOwn_true());
    if (OgrPINVOKE.SWIGPendingException.Pending) throw OgrPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int SetNextByIndex(long new_index) {
    int ret = OgrPINVOKE.Layer_SetNextByIndex(swigCPtr, new_index);
    if (OgrPINVOKE.SWIGPendingException.Pending) throw OgrPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int SetFeature(Feature feature) {
    int ret = OgrPINVOKE.Layer_SetFeature(swigCPtr, Feature.getCPtr(feature));
    if (OgrPINVOKE.SWIGPendingException.Pending) throw OgrPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int CreateFeature(Feature feature) {
    int ret = OgrPINVOKE.Layer_CreateFeature(swigCPtr, Feature.getCPtr(feature));
    if (OgrPINVOKE.SWIGPendingException.Pending) throw OgrPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int UpsertFeature(Feature feature) {
    int ret = OgrPINVOKE.Layer_UpsertFeature(swigCPtr, Feature.getCPtr(feature));
    if (OgrPINVOKE.SWIGPendingException.Pending) throw OgrPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int UpdateFeature(Feature feature, int nUpdatedFieldsCount, int[] panUpdatedFieldsIdx, int nUpdatedGeomFieldsCount, int[] panUpdatedGeomFieldsIdx, bool bUpdateStyleString) {
    GCHandle swig_handleTo_panUpdatedFieldsIdx = GCHandle.Alloc(panUpdatedFieldsIdx, GCHandleType.Pinned);
    try {
    GCHandle swig_handleTo_panUpdatedGeomFieldsIdx = GCHandle.Alloc(panUpdatedGeomFieldsIdx, GCHandleType.Pinned);
    try {
    {
      int ret = OgrPINVOKE.Layer_UpdateFeature(swigCPtr, Feature.getCPtr(feature), nUpdatedFieldsCount, swig_handleTo_panUpdatedFieldsIdx.AddrOfPinnedObject(), nUpdatedGeomFieldsCount, swig_handleTo_panUpdatedGeomFieldsIdx.AddrOfPinnedObject(), bUpdateStyleString);
      if (OgrPINVOKE.SWIGPendingException.Pending) throw OgrPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    }
    } finally {
        swig_handleTo_panUpdatedGeomFieldsIdx.Free();
        GC.KeepAlive(this);
    }
    } finally {
        swig_handleTo_panUpdatedFieldsIdx.Free();
        GC.KeepAlive(this);
    }
  }

  public int DeleteFeature(long fid) {
    int ret = OgrPINVOKE.Layer_DeleteFeature(swigCPtr, fid);
    if (OgrPINVOKE.SWIGPendingException.Pending) throw OgrPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int SyncToDisk() {
    int ret = OgrPINVOKE.Layer_SyncToDisk(swigCPtr);
    if (OgrPINVOKE.SWIGPendingException.Pending) throw OgrPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public FeatureDefn GetLayerDefn() {
    IntPtr cPtr = OgrPINVOKE.Layer_GetLayerDefn(swigCPtr);
    FeatureDefn ret = (cPtr == IntPtr.Zero) ? null : new FeatureDefn(cPtr, true, ThisOwn_true());
    if (OgrPINVOKE.SWIGPendingException.Pending) throw OgrPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public long GetFeatureCount(int force) {
    long res = OgrPINVOKE.Layer_GetFeatureCount(swigCPtr, force);
    if (OgrPINVOKE.SWIGPendingException.Pending) throw OgrPINVOKE.SWIGPendingException.Retrieve();
    return res;
}

  public int GetExtent(Envelope extent, int force) {
    int ret = OgrPINVOKE.Layer_GetExtent(swigCPtr, Envelope.getCPtr(extent), force);
    if (OgrPINVOKE.SWIGPendingException.Pending) throw OgrPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool TestCapability(string cap) {
    IntPtr tempcap = OgrPINVOKE.StringToUtf8Unmanaged(cap);
    try {
      bool ret = OgrPINVOKE.Layer_TestCapability(swigCPtr, tempcap);
      if (OgrPINVOKE.SWIGPendingException.Pending) throw OgrPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } finally {
    System.Runtime.InteropServices.Marshal.FreeHGlobal(tempcap);
    }
  }

  public int CreateField(FieldDefn field_def, int approx_ok) {
    int ret = OgrPINVOKE.Layer_CreateField(swigCPtr, FieldDefn.getCPtr(field_def), approx_ok);
    if (OgrPINVOKE.SWIGPendingException.Pending) throw OgrPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int DeleteField(int iField) {
    int ret = OgrPINVOKE.Layer_DeleteField(swigCPtr, iField);
    if (OgrPINVOKE.SWIGPendingException.Pending) throw OgrPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int ReorderField(int iOldFieldPos, int iNewFieldPos) {
    int ret = OgrPINVOKE.Layer_ReorderField(swigCPtr, iOldFieldPos, iNewFieldPos);
    if (OgrPINVOKE.SWIGPendingException.Pending) throw OgrPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int ReorderFields(int nList, int[] pList) {
    int ret = OgrPINVOKE.Layer_ReorderFields(swigCPtr, nList, pList);
    if (OgrPINVOKE.SWIGPendingException.Pending) throw OgrPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int AlterFieldDefn(int iField, FieldDefn field_def, int nFlags) {
    int ret = OgrPINVOKE.Layer_AlterFieldDefn(swigCPtr, iField, FieldDefn.getCPtr(field_def), nFlags);
    if (OgrPINVOKE.SWIGPendingException.Pending) throw OgrPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int AlterGeomFieldDefn(int iGeomField, GeomFieldDefn field_def, int nFlags) {
    int ret = OgrPINVOKE.Layer_AlterGeomFieldDefn(swigCPtr, iGeomField, GeomFieldDefn.getCPtr(field_def), nFlags);
    if (OgrPINVOKE.SWIGPendingException.Pending) throw OgrPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int CreateGeomField(GeomFieldDefn field_def, int approx_ok) {
    int ret = OgrPINVOKE.Layer_CreateGeomField(swigCPtr, GeomFieldDefn.getCPtr(field_def), approx_ok);
    if (OgrPINVOKE.SWIGPendingException.Pending) throw OgrPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int StartTransaction() {
    int ret = OgrPINVOKE.Layer_StartTransaction(swigCPtr);
    if (OgrPINVOKE.SWIGPendingException.Pending) throw OgrPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int CommitTransaction() {
    int ret = OgrPINVOKE.Layer_CommitTransaction(swigCPtr);
    if (OgrPINVOKE.SWIGPendingException.Pending) throw OgrPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int RollbackTransaction() {
    int ret = OgrPINVOKE.Layer_RollbackTransaction(swigCPtr);
    if (OgrPINVOKE.SWIGPendingException.Pending) throw OgrPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int FindFieldIndex(string pszFieldName, int bExactMatch) {
    IntPtr temppszFieldName = OgrPINVOKE.StringToUtf8Unmanaged(pszFieldName);
    try {
      int ret = OgrPINVOKE.Layer_FindFieldIndex(swigCPtr, temppszFieldName, bExactMatch);
      if (OgrPINVOKE.SWIGPendingException.Pending) throw OgrPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } finally {
    System.Runtime.InteropServices.Marshal.FreeHGlobal(temppszFieldName);
    }
  }

  public OSGeo.OSR.SpatialReference GetSpatialRef() {
    IntPtr cPtr = OgrPINVOKE.Layer_GetSpatialRef(swigCPtr);
    OSGeo.OSR.SpatialReference ret = (cPtr == IntPtr.Zero) ? null : new OSGeo.OSR.SpatialReference(cPtr, true, ThisOwn_true());
    if (OgrPINVOKE.SWIGPendingException.Pending) throw OgrPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public long GetFeaturesRead() {
    long res = OgrPINVOKE.Layer_GetFeaturesRead(swigCPtr);
    if (OgrPINVOKE.SWIGPendingException.Pending) throw OgrPINVOKE.SWIGPendingException.Retrieve();
    return res;
}

  public int SetIgnoredFields(string[] options) {
    using (var tempoptions = new OgrPINVOKE.StringListMarshal(options)) { 
    {
      int ret = OgrPINVOKE.Layer_SetIgnoredFields(swigCPtr, tempoptions._ar);
      if (OgrPINVOKE.SWIGPendingException.Pending) throw OgrPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    }
    }
  }

  public int Intersection(Layer method_layer, Layer result_layer, string[] options, Ogr.GDALProgressFuncDelegate callback, string callback_data) {
    using (var tempoptions = new OgrPINVOKE.StringListMarshal(options)) { 
    IntPtr tempcallback_data = OgrPINVOKE.StringToUtf8Unmanaged(callback_data);
    try {
      int ret = OgrPINVOKE.Layer_Intersection(swigCPtr, Layer.getCPtr(method_layer), Layer.getCPtr(result_layer), tempoptions._ar, callback, tempcallback_data);
      if (OgrPINVOKE.SWIGPendingException.Pending) throw OgrPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } finally {
    System.Runtime.InteropServices.Marshal.FreeHGlobal(tempcallback_data);
    }
    }
  }

  public int Union(Layer method_layer, Layer result_layer, string[] options, Ogr.GDALProgressFuncDelegate callback, string callback_data) {
    using (var tempoptions = new OgrPINVOKE.StringListMarshal(options)) { 
    IntPtr tempcallback_data = OgrPINVOKE.StringToUtf8Unmanaged(callback_data);
    try {
      int ret = OgrPINVOKE.Layer_Union(swigCPtr, Layer.getCPtr(method_layer), Layer.getCPtr(result_layer), tempoptions._ar, callback, tempcallback_data);
      if (OgrPINVOKE.SWIGPendingException.Pending) throw OgrPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } finally {
    System.Runtime.InteropServices.Marshal.FreeHGlobal(tempcallback_data);
    }
    }
  }

  public int SymDifference(Layer method_layer, Layer result_layer, string[] options, Ogr.GDALProgressFuncDelegate callback, string callback_data) {
    using (var tempoptions = new OgrPINVOKE.StringListMarshal(options)) { 
    IntPtr tempcallback_data = OgrPINVOKE.StringToUtf8Unmanaged(callback_data);
    try {
      int ret = OgrPINVOKE.Layer_SymDifference(swigCPtr, Layer.getCPtr(method_layer), Layer.getCPtr(result_layer), tempoptions._ar, callback, tempcallback_data);
      if (OgrPINVOKE.SWIGPendingException.Pending) throw OgrPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } finally {
    System.Runtime.InteropServices.Marshal.FreeHGlobal(tempcallback_data);
    }
    }
  }

  public int Identity(Layer method_layer, Layer result_layer, string[] options, Ogr.GDALProgressFuncDelegate callback, string callback_data) {
    using (var tempoptions = new OgrPINVOKE.StringListMarshal(options)) { 
    IntPtr tempcallback_data = OgrPINVOKE.StringToUtf8Unmanaged(callback_data);
    try {
      int ret = OgrPINVOKE.Layer_Identity(swigCPtr, Layer.getCPtr(method_layer), Layer.getCPtr(result_layer), tempoptions._ar, callback, tempcallback_data);
      if (OgrPINVOKE.SWIGPendingException.Pending) throw OgrPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } finally {
    System.Runtime.InteropServices.Marshal.FreeHGlobal(tempcallback_data);
    }
    }
  }

  public int Update(Layer method_layer, Layer result_layer, string[] options, Ogr.GDALProgressFuncDelegate callback, string callback_data) {
    using (var tempoptions = new OgrPINVOKE.StringListMarshal(options)) { 
    IntPtr tempcallback_data = OgrPINVOKE.StringToUtf8Unmanaged(callback_data);
    try {
      int ret = OgrPINVOKE.Layer_Update(swigCPtr, Layer.getCPtr(method_layer), Layer.getCPtr(result_layer), tempoptions._ar, callback, tempcallback_data);
      if (OgrPINVOKE.SWIGPendingException.Pending) throw OgrPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } finally {
    System.Runtime.InteropServices.Marshal.FreeHGlobal(tempcallback_data);
    }
    }
  }

  public int Clip(Layer method_layer, Layer result_layer, string[] options, Ogr.GDALProgressFuncDelegate callback, string callback_data) {
    using (var tempoptions = new OgrPINVOKE.StringListMarshal(options)) { 
    IntPtr tempcallback_data = OgrPINVOKE.StringToUtf8Unmanaged(callback_data);
    try {
      int ret = OgrPINVOKE.Layer_Clip(swigCPtr, Layer.getCPtr(method_layer), Layer.getCPtr(result_layer), tempoptions._ar, callback, tempcallback_data);
      if (OgrPINVOKE.SWIGPendingException.Pending) throw OgrPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } finally {
    System.Runtime.InteropServices.Marshal.FreeHGlobal(tempcallback_data);
    }
    }
  }

  public int Erase(Layer method_layer, Layer result_layer, string[] options, Ogr.GDALProgressFuncDelegate callback, string callback_data) {
    using (var tempoptions = new OgrPINVOKE.StringListMarshal(options)) { 
    IntPtr tempcallback_data = OgrPINVOKE.StringToUtf8Unmanaged(callback_data);
    try {
      int ret = OgrPINVOKE.Layer_Erase(swigCPtr, Layer.getCPtr(method_layer), Layer.getCPtr(result_layer), tempoptions._ar, callback, tempcallback_data);
      if (OgrPINVOKE.SWIGPendingException.Pending) throw OgrPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } finally {
    System.Runtime.InteropServices.Marshal.FreeHGlobal(tempcallback_data);
    }
    }
  }

  public StyleTable GetStyleTable() {
    IntPtr cPtr = OgrPINVOKE.Layer_GetStyleTable(swigCPtr);
    StyleTable ret = (cPtr == IntPtr.Zero) ? null : new StyleTable(cPtr, false, ThisOwn_false());
    if (OgrPINVOKE.SWIGPendingException.Pending) throw OgrPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetStyleTable(StyleTable table) {
    OgrPINVOKE.Layer_SetStyleTable(swigCPtr, StyleTable.getCPtr(table));
    if (OgrPINVOKE.SWIGPendingException.Pending) throw OgrPINVOKE.SWIGPendingException.Retrieve();
  }

  public int SetActiveSRS(int geom_field, OSGeo.OSR.SpatialReference srs) {
    int ret = OgrPINVOKE.Layer_SetActiveSRS(swigCPtr, geom_field, OSGeo.OSR.SpatialReference.getCPtr(srs));
    if (OgrPINVOKE.SWIGPendingException.Pending) throw OgrPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
